// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/academic/domain"
	mock "github.com/stretchr/testify/mock"
)

// AcademicYearService is an autogenerated mock type for the AcademicYearService type
type AcademicYearService struct {
	mock.Mock
}

// AssignClasses provides a mock function with given fields: ctx, ayID, classIDs
func (_m *AcademicYearService) AssignClasses(ctx context.Context, ayID uint, classIDs []uint) error {
	ret := _m.Called(ctx, ayID, classIDs)

	if len(ret) == 0 {
		panic("no return value specified for AssignClasses")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, []uint) error); ok {
		r0 = rf(ctx, ayID, classIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AssignMajors provides a mock function with given fields: ctx, ayID, majorIDs
func (_m *AcademicYearService) AssignMajors(ctx context.Context, ayID uint, majorIDs []uint) error {
	ret := _m.Called(ctx, ayID, majorIDs)

	if len(ret) == 0 {
		panic("no return value specified for AssignMajors")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, []uint) error); ok {
		r0 = rf(ctx, ayID, majorIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BulkDelete provides a mock function with given fields: ctx, ids
func (_m *AcademicYearService) BulkDelete(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BulkRestore provides a mock function with given fields: ctx, ids
func (_m *AcademicYearService) BulkRestore(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkRestore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, ay
func (_m *AcademicYearService) Create(ctx context.Context, ay *domain.AcademicYear) error {
	ret := _m.Called(ctx, ay)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AcademicYear) error); ok {
		r0 = rf(ctx, ay)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *AcademicYearService) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetActive provides a mock function with given fields: ctx
func (_m *AcademicYearService) GetActive(ctx context.Context) ([]domain.AcademicYear, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetActive")
	}

	var r0 []domain.AcademicYear
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.AcademicYear, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.AcademicYear); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AcademicYear)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx, page, limit, search, status
func (_m *AcademicYearService) GetAll(ctx context.Context, page int, limit int, search string, status string, sort string) ([]domain.AcademicYear, int, error) {
	ret := _m.Called(ctx, page, limit, search, status, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.AcademicYear
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string) ([]domain.AcademicYear, int, error)); ok {
		return rf(ctx, page, limit, search, status, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string) []domain.AcademicYear); ok {
		r0 = rf(ctx, page, limit, search, status, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AcademicYear)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, string) int); ok {
		r1 = rf(ctx, page, limit, search, status, sort)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string, string) error); ok {
		r2 = rf(ctx, page, limit, search, status, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetClassesByYear provides a mock function with given fields: ctx, ayID
func (_m *AcademicYearService) GetClassesByYear(ctx context.Context, ayID uint) ([]domain.Class, error) {
	ret := _m.Called(ctx, ayID)

	if len(ret) == 0 {
		panic("no return value specified for GetClassesByYear")
	}

	var r0 []domain.Class
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.Class, error)); ok {
		return rf(ctx, ayID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.Class); ok {
		r0 = rf(ctx, ayID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Class)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, ayID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDependencyInfo provides a mock function with given fields: ctx, id
func (_m *AcademicYearService) GetDependencyInfo(ctx context.Context, id uint) (map[string]interface{}, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDependencyInfo")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (map[string]interface{}, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) map[string]interface{}); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMajorsByYear provides a mock function with given fields: ctx, ayID
func (_m *AcademicYearService) GetMajorsByYear(ctx context.Context, ayID uint) ([]domain.Major, error) {
	ret := _m.Called(ctx, ayID)

	if len(ret) == 0 {
		panic("no return value specified for GetMajorsByYear")
	}

	var r0 []domain.Major
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.Major, error)); ok {
		return rf(ctx, ayID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.Major); ok {
		r0 = rf(ctx, ayID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Major)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, ayID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Restore provides a mock function with given fields: ctx, id
func (_m *AcademicYearService) Restore(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, ay
func (_m *AcademicYearService) Update(ctx context.Context, ay *domain.AcademicYear) error {
	ret := _m.Called(ctx, ay)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.AcademicYear) error); ok {
		r0 = rf(ctx, ay)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckUnique provides a mock function with given fields: ctx, year, excludeID
func (_m *AcademicYearService) CheckUnique(ctx context.Context, year int, excludeID uint) (bool, error) {
	ret := _m.Called(ctx, year, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for CheckUnique")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, uint) bool); ok {
		r0 = rf(ctx, year, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, uint) error); ok {
		r1 = rf(ctx, year, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAcademicYearService creates a new instance of AcademicYearService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAcademicYearService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AcademicYearService {
	mock := &AcademicYearService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
