// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	auditdomain "github.com/ahmadzakyarifin/schoolpay/internal/module/audit/domain"
	bun "github.com/uptrace/bun"

	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/user_auth/domain"

	mock "github.com/stretchr/testify/mock"
)

// MockAuditLogService is an autogenerated mock type for the AuditLogService type
type MockAuditLogService struct {
	mock.Mock
}

type MockAuditLogService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuditLogService) EXPECT() *MockAuditLogService_Expecter {
	return &MockAuditLogService_Expecter{mock: &_m.Mock}
}

// GetEntityLogs provides a mock function with given fields: ctx, currentUser, entityType, entityID
func (_m *MockAuditLogService) GetEntityLogs(ctx context.Context, currentUser *domain.User, entityType string, entityID uint) ([]auditdomain.AuditLog, error) {
	ret := _m.Called(ctx, currentUser, entityType, entityID)

	if len(ret) == 0 {
		panic("no return value specified for GetEntityLogs")
	}

	var r0 []auditdomain.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, string, uint) ([]auditdomain.AuditLog, error)); ok {
		return rf(ctx, currentUser, entityType, entityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, string, uint) []auditdomain.AuditLog); ok {
		r0 = rf(ctx, currentUser, entityType, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]auditdomain.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.User, string, uint) error); ok {
		r1 = rf(ctx, currentUser, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuditLogService_GetEntityLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntityLogs'
type MockAuditLogService_GetEntityLogs_Call struct {
	*mock.Call
}

// GetEntityLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - currentUser *domain.User
//   - entityType string
//   - entityID uint
func (_e *MockAuditLogService_Expecter) GetEntityLogs(ctx interface{}, currentUser interface{}, entityType interface{}, entityID interface{}) *MockAuditLogService_GetEntityLogs_Call {
	return &MockAuditLogService_GetEntityLogs_Call{Call: _e.mock.On("GetEntityLogs", ctx, currentUser, entityType, entityID)}
}

func (_c *MockAuditLogService_GetEntityLogs_Call) Run(run func(ctx context.Context, currentUser *domain.User, entityType string, entityID uint)) *MockAuditLogService_GetEntityLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User), args[2].(string), args[3].(uint))
	})
	return _c
}

func (_c *MockAuditLogService_GetEntityLogs_Call) Return(_a0 []auditdomain.AuditLog, _a1 error) *MockAuditLogService_GetEntityLogs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuditLogService_GetEntityLogs_Call) RunAndReturn(run func(context.Context, *domain.User, string, uint) ([]auditdomain.AuditLog, error)) *MockAuditLogService_GetEntityLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetLogs provides a mock function with given fields: ctx, currentUser, filter, page, limit
func (_m *MockAuditLogService) GetLogs(ctx context.Context, currentUser *domain.User, filter map[string]interface{}, page int, limit int) ([]auditdomain.AuditLog, int, error) {
	ret := _m.Called(ctx, currentUser, filter, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 []auditdomain.AuditLog
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, map[string]interface{}, int, int) ([]auditdomain.AuditLog, int, error)); ok {
		return rf(ctx, currentUser, filter, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, map[string]interface{}, int, int) []auditdomain.AuditLog); ok {
		r0 = rf(ctx, currentUser, filter, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]auditdomain.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.User, map[string]interface{}, int, int) int); ok {
		r1 = rf(ctx, currentUser, filter, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *domain.User, map[string]interface{}, int, int) error); ok {
		r2 = rf(ctx, currentUser, filter, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockAuditLogService_GetLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLogs'
type MockAuditLogService_GetLogs_Call struct {
	*mock.Call
}

// GetLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - currentUser *domain.User
//   - filter map[string]interface{}
//   - page int
//   - limit int
func (_e *MockAuditLogService_Expecter) GetLogs(ctx interface{}, currentUser interface{}, filter interface{}, page interface{}, limit interface{}) *MockAuditLogService_GetLogs_Call {
	return &MockAuditLogService_GetLogs_Call{Call: _e.mock.On("GetLogs", ctx, currentUser, filter, page, limit)}
}

func (_c *MockAuditLogService_GetLogs_Call) Run(run func(ctx context.Context, currentUser *domain.User, filter map[string]interface{}, page int, limit int)) *MockAuditLogService_GetLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.User), args[2].(map[string]interface{}), args[3].(int), args[4].(int))
	})
	return _c
}

func (_c *MockAuditLogService_GetLogs_Call) Return(_a0 []auditdomain.AuditLog, _a1 int, _a2 error) *MockAuditLogService_GetLogs_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockAuditLogService_GetLogs_Call) RunAndReturn(run func(context.Context, *domain.User, map[string]interface{}, int, int) ([]auditdomain.AuditLog, int, error)) *MockAuditLogService_GetLogs_Call {
	_c.Call.Return(run)
	return _c
}

// Log provides a mock function with given fields: ctx, db, userID, userName, role, action, entityType, entityID, oldValues, newValues, ipAddress, userAgent
func (_m *MockAuditLogService) Log(ctx context.Context, db bun.IDB, userID uint, userName string, role string, action string, entityType string, entityID uint, oldValues map[string]interface{}, newValues map[string]interface{}, ipAddress string, userAgent string) error {
	ret := _m.Called(ctx, db, userID, userName, role, action, entityType, entityID, oldValues, newValues, ipAddress, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uint, string, string, string, string, uint, map[string]interface{}, map[string]interface{}, string, string) error); ok {
		r0 = rf(ctx, db, userID, userName, role, action, entityType, entityID, oldValues, newValues, ipAddress, userAgent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuditLogService_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type MockAuditLogService_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - ctx context.Context
//   - db bun.IDB
//   - userID uint
//   - userName string
//   - role string
//   - action string
//   - entityType string
//   - entityID uint
//   - oldValues map[string]interface{}
//   - newValues map[string]interface{}
//   - ipAddress string
//   - userAgent string
func (_e *MockAuditLogService_Expecter) Log(ctx interface{}, db interface{}, userID interface{}, userName interface{}, role interface{}, action interface{}, entityType interface{}, entityID interface{}, oldValues interface{}, newValues interface{}, ipAddress interface{}, userAgent interface{}) *MockAuditLogService_Log_Call {
	return &MockAuditLogService_Log_Call{Call: _e.mock.On("Log", ctx, db, userID, userName, role, action, entityType, entityID, oldValues, newValues, ipAddress, userAgent)}
}

func (_c *MockAuditLogService_Log_Call) Run(run func(ctx context.Context, db bun.IDB, userID uint, userName string, role string, action string, entityType string, entityID uint, oldValues map[string]interface{}, newValues map[string]interface{}, ipAddress string, userAgent string)) *MockAuditLogService_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bun.IDB), args[2].(uint), args[3].(string), args[4].(string), args[5].(string), args[6].(string), args[7].(uint), args[8].(map[string]interface{}), args[9].(map[string]interface{}), args[10].(string), args[11].(string))
	})
	return _c
}

func (_c *MockAuditLogService_Log_Call) Return(_a0 error) *MockAuditLogService_Log_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuditLogService_Log_Call) RunAndReturn(run func(context.Context, bun.IDB, uint, string, string, string, string, uint, map[string]interface{}, map[string]interface{}, string, string) error) *MockAuditLogService_Log_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuditLogService creates a new instance of MockAuditLogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuditLogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuditLogService {
	mock := &MockAuditLogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
