// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bun "github.com/uptrace/bun"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/audit/domain"
	mock "github.com/stretchr/testify/mock"
)

// AuditLogRepo is an autogenerated mock type for the AuditLogRepo type
type AuditLogRepo struct {
	mock.Mock
}

// FindAll provides a mock function with given fields: ctx, filter, page, limit
func (_m *AuditLogRepo) FindAll(ctx context.Context, filter map[string]interface{}, page int, limit int) ([]domain.AuditLog, int, error) {
	ret := _m.Called(ctx, filter, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.AuditLog
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}, int, int) ([]domain.AuditLog, int, error)); ok {
		return rf(ctx, filter, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}, int, int) []domain.AuditLog); ok {
		r0 = rf(ctx, filter, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, map[string]interface{}, int, int) int); ok {
		r1 = rf(ctx, filter, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, map[string]interface{}, int, int) error); ok {
		r2 = rf(ctx, filter, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByEntity provides a mock function with given fields: ctx, entityType, entityID
func (_m *AuditLogRepo) FindByEntity(ctx context.Context, entityType string, entityID uint) ([]domain.AuditLog, error) {
	ret := _m.Called(ctx, entityType, entityID)

	if len(ret) == 0 {
		panic("no return value specified for FindByEntity")
	}

	var r0 []domain.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) ([]domain.AuditLog, error)); ok {
		return rf(ctx, entityType, entityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) []domain.AuditLog); ok {
		r0 = rf(ctx, entityType, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = rf(ctx, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Log provides a mock function with given fields: ctx, db, al
func (_m *AuditLogRepo) Log(ctx context.Context, db bun.IDB, al *domain.AuditLog) error {
	ret := _m.Called(ctx, db, al)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *domain.AuditLog) error); ok {
		r0 = rf(ctx, db, al)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuditLogRepo creates a new instance of AuditLogRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLogRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLogRepo {
	mock := &AuditLogRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
