// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	dto "github.com/ahmadzakyarifin/schoolpay/internal/dto"
	auditdomain "github.com/ahmadzakyarifin/schoolpay/internal/module/audit/domain"
	bun "github.com/uptrace/bun"

	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/user_auth/domain"

	mock "github.com/stretchr/testify/mock"
)

// AuditLogService is an autogenerated mock type for the AuditLogService type
type AuditLogService struct {
	mock.Mock
}

// GetEntityLogs provides a mock function with given fields: ctx, currentUser, entityType, entityID
func (_m *AuditLogService) GetEntityLogs(ctx context.Context, currentUser *domain.User, entityType string, entityID uint) ([]auditdomain.AuditLog, error) {
	ret := _m.Called(ctx, currentUser, entityType, entityID)

	if len(ret) == 0 {
		panic("no return value specified for GetEntityLogs")
	}

	var r0 []auditdomain.AuditLog
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, string, uint) ([]auditdomain.AuditLog, error)); ok {
		return rf(ctx, currentUser, entityType, entityID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, string, uint) []auditdomain.AuditLog); ok {
		r0 = rf(ctx, currentUser, entityType, entityID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]auditdomain.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.User, string, uint) error); ok {
		r1 = rf(ctx, currentUser, entityType, entityID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLogs provides a mock function with given fields: ctx, currentUser, filter, page, limit
func (_m *AuditLogService) GetLogs(ctx context.Context, currentUser *domain.User, filter map[string]interface{}, page int, limit int) ([]auditdomain.AuditLog, int, error) {
	ret := _m.Called(ctx, currentUser, filter, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLogs")
	}

	var r0 []auditdomain.AuditLog
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, map[string]interface{}, int, int) ([]auditdomain.AuditLog, int, error)); ok {
		return rf(ctx, currentUser, filter, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, map[string]interface{}, int, int) []auditdomain.AuditLog); ok {
		r0 = rf(ctx, currentUser, filter, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]auditdomain.AuditLog)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.User, map[string]interface{}, int, int) int); ok {
		r1 = rf(ctx, currentUser, filter, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *domain.User, map[string]interface{}, int, int) error); ok {
		r2 = rf(ctx, currentUser, filter, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Log provides a mock function with given fields: ctx, db, userID, userName, role, action, entityType, entityID, oldValues, newValues, ipAddress, userAgent
func (_m *AuditLogService) Log(ctx context.Context, db bun.IDB, userID uint, userName string, role string, action string, entityType string, entityID uint, oldValues map[string]interface{}, newValues map[string]interface{}, ipAddress string, userAgent string) error {
	ret := _m.Called(ctx, db, userID, userName, role, action, entityType, entityID, oldValues, newValues, ipAddress, userAgent)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uint, string, string, string, string, uint, map[string]interface{}, map[string]interface{}, string, string) error); ok {
		r0 = rf(ctx, db, userID, userName, role, action, entityType, entityID, oldValues, newValues, ipAddress, userAgent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogMeta provides a mock function with given fields: ctx, db, audit, action, entityType, entityID, oldValues, newValues, description
func (_m *AuditLogService) LogMeta(ctx context.Context, db bun.IDB, audit dto.AuditMeta, action string, entityType string, entityID uint, oldValues map[string]interface{}, newValues map[string]interface{}, description string) error {
	ret := _m.Called(ctx, db, audit, action, entityType, entityID, oldValues, newValues, description)

	if len(ret) == 0 {
		panic("no return value specified for LogMeta")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, dto.AuditMeta, string, string, uint, map[string]interface{}, map[string]interface{}, string) error); ok {
		r0 = rf(ctx, db, audit, action, entityType, entityID, oldValues, newValues, description)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuditLogService creates a new instance of AuditLogService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuditLogService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuditLogService {
	mock := &AuditLogService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
