// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	config "github.com/ahmadzakyarifin/schoolpay/config"

	dto "github.com/ahmadzakyarifin/schoolpay/internal/dto"

	mock "github.com/stretchr/testify/mock"
)

// AuthService is an autogenerated mock type for the AuthService type
type AuthService struct {
	mock.Mock
}

// ChangePassword provides a mock function with given fields: ctx, userID, currentPassword, newPassword, audit
func (_m *AuthService) ChangePassword(ctx context.Context, userID uint, currentPassword string, newPassword string, audit dto.AuditMeta) error {
	ret := _m.Called(ctx, userID, currentPassword, newPassword, audit)

	if len(ret) == 0 {
		panic("no return value specified for ChangePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, dto.AuditMeta) error); ok {
		r0 = rf(ctx, userID, currentPassword, newPassword, audit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ForgotPassword provides a mock function with given fields: ctx, req, audit, cfg
func (_m *AuthService) ForgotPassword(ctx context.Context, req dto.ForgotPasswordRequest, audit dto.AuditMeta, cfg *config.Config) error {
	ret := _m.Called(ctx, req, audit, cfg)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ForgotPasswordRequest, dto.AuditMeta, *config.Config) error); ok {
		r0 = rf(ctx, req, audit, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Login provides a mock function with given fields: ctx, req, audit, jwtSecret
func (_m *AuthService) Login(ctx context.Context, req dto.LoginRequest, audit dto.AuditMeta, jwtSecret string) (*dto.LoginResponse, error) {
	ret := _m.Called(ctx, req, audit, jwtSecret)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *dto.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.LoginRequest, dto.AuditMeta, string) (*dto.LoginResponse, error)); ok {
		return rf(ctx, req, audit, jwtSecret)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dto.LoginRequest, dto.AuditMeta, string) *dto.LoginResponse); ok {
		r0 = rf(ctx, req, audit, jwtSecret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, dto.LoginRequest, dto.AuditMeta, string) error); ok {
		r1 = rf(ctx, req, audit, jwtSecret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Logout provides a mock function with given fields: ctx, refreshToken
func (_m *AuthService) Logout(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshToken provides a mock function with given fields: ctx, refreshToken, audit, jwtSecret
func (_m *AuthService) RefreshToken(ctx context.Context, refreshToken string, audit dto.AuditMeta, jwtSecret string) (*dto.LoginResponse, error) {
	ret := _m.Called(ctx, refreshToken, audit, jwtSecret)

	if len(ret) == 0 {
		panic("no return value specified for RefreshToken")
	}

	var r0 *dto.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.AuditMeta, string) (*dto.LoginResponse, error)); ok {
		return rf(ctx, refreshToken, audit, jwtSecret)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, dto.AuditMeta, string) *dto.LoginResponse); ok {
		r0 = rf(ctx, refreshToken, audit, jwtSecret)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, dto.AuditMeta, string) error); ok {
		r1 = rf(ctx, refreshToken, audit, jwtSecret)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResetPassword provides a mock function with given fields: ctx, req, audit
func (_m *AuthService) ResetPassword(ctx context.Context, req dto.ResetPasswordRequest, audit dto.AuditMeta) error {
	ret := _m.Called(ctx, req, audit)

	if len(ret) == 0 {
		panic("no return value specified for ResetPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dto.ResetPasswordRequest, dto.AuditMeta) error); ok {
		r0 = rf(ctx, req, audit)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthService creates a new instance of AuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthService {
	mock := &AuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
