// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/finance/domain"
	mock "github.com/stretchr/testify/mock"
)

// BillingRuleRepo is an autogenerated mock type for the BillingRuleRepo type
type BillingRuleRepo struct {
	mock.Mock
}

// BulkDelete provides a mock function with given fields: ctx, ids
func (_m *BillingRuleRepo) BulkDelete(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BulkRestore provides a mock function with given fields: ctx, ids
func (_m *BillingRuleRepo) BulkRestore(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkRestore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountStudentBills provides a mock function with given fields: ctx, ruleID
func (_m *BillingRuleRepo) CountStudentBills(ctx context.Context, ruleID uint) (int, error) {
	ret := _m.Called(ctx, ruleID)

	if len(ret) == 0 {
		panic("no return value specified for CountStudentBills")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int, error)); ok {
		return rf(ctx, ruleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int); ok {
		r0 = rf(ctx, ruleID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, ruleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, br
func (_m *BillingRuleRepo) Create(ctx context.Context, br *domain.BillingRule) error {
	ret := _m.Called(ctx, br)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BillingRule) error); ok {
		r0 = rf(ctx, br)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *BillingRuleRepo) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, btID, targetType, targetID, classID
func (_m *BillingRuleRepo) Exists(ctx context.Context, btID uint, targetType string, targetID uint, classID *uint) (bool, error) {
	ret := _m.Called(ctx, btID, targetType, targetID, classID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, uint, *uint) (bool, error)); ok {
		return rf(ctx, btID, targetType, targetID, classID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, uint, *uint) bool); ok {
		r0 = rf(ctx, btID, targetType, targetID, classID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string, uint, *uint) error); ok {
		r1 = rf(ctx, btID, targetType, targetID, classID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExistsExcludeID provides a mock function with given fields: ctx, btID, targetType, targetID, classID, excludeID
func (_m *BillingRuleRepo) ExistsExcludeID(ctx context.Context, btID uint, targetType string, targetID uint, classID *uint, excludeID uint) (bool, error) {
	ret := _m.Called(ctx, btID, targetType, targetID, classID, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsExcludeID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, uint, *uint, uint) (bool, error)); ok {
		return rf(ctx, btID, targetType, targetID, classID, excludeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, uint, *uint, uint) bool); ok {
		r0 = rf(ctx, btID, targetType, targetID, classID, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string, uint, *uint, uint) error); ok {
		r1 = rf(ctx, btID, targetType, targetID, classID, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx
func (_m *BillingRuleRepo) FindAll(ctx context.Context) ([]domain.BillingRule, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.BillingRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.BillingRule, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.BillingRule); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BillingRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllPaged provides a mock function with given fields: ctx, page, limit, search, status, generateStatus, sort
func (_m *BillingRuleRepo) FindAllPaged(ctx context.Context, page int, limit int, search string, status string, generateStatus string, sort string) ([]domain.BillingRule, int, error) {
	ret := _m.Called(ctx, page, limit, search, status, generateStatus, sort)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaged")
	}

	var r0 []domain.BillingRule
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string) ([]domain.BillingRule, int, error)); ok {
		return rf(ctx, page, limit, search, status, generateStatus, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string) []domain.BillingRule); ok {
		r0 = rf(ctx, page, limit, search, status, generateStatus, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BillingRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, string, string) int); ok {
		r1 = rf(ctx, page, limit, search, status, generateStatus, sort)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string, string, string) error); ok {
		r2 = rf(ctx, page, limit, search, status, generateStatus, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *BillingRuleRepo) FindByID(ctx context.Context, id uint) (*domain.BillingRule, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.BillingRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.BillingRule, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.BillingRule); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BillingRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Restore provides a mock function with given fields: ctx, id
func (_m *BillingRuleRepo) Restore(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ToggleStatus provides a mock function with given fields: ctx, id
func (_m *BillingRuleRepo) ToggleStatus(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ToggleStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, br
func (_m *BillingRuleRepo) Update(ctx context.Context, br *domain.BillingRule) error {
	ret := _m.Called(ctx, br)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BillingRule) error); ok {
		r0 = rf(ctx, br)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBillingRuleRepo creates a new instance of BillingRuleRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBillingRuleRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *BillingRuleRepo {
	mock := &BillingRuleRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
