// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/finance/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockBillTypeRepo is an autogenerated mock type for the BillTypeRepo type
type MockBillTypeRepo struct {
	mock.Mock
}

type MockBillTypeRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBillTypeRepo) EXPECT() *MockBillTypeRepo_Expecter {
	return &MockBillTypeRepo_Expecter{mock: &_m.Mock}
}

// BulkDelete provides a mock function with given fields: ctx, ids
func (_m *MockBillTypeRepo) BulkDelete(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillTypeRepo_BulkDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkDelete'
type MockBillTypeRepo_BulkDelete_Call struct {
	*mock.Call
}

// BulkDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint
func (_e *MockBillTypeRepo_Expecter) BulkDelete(ctx interface{}, ids interface{}) *MockBillTypeRepo_BulkDelete_Call {
	return &MockBillTypeRepo_BulkDelete_Call{Call: _e.mock.On("BulkDelete", ctx, ids)}
}

func (_c *MockBillTypeRepo_BulkDelete_Call) Run(run func(ctx context.Context, ids []uint)) *MockBillTypeRepo_BulkDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint))
	})
	return _c
}

func (_c *MockBillTypeRepo_BulkDelete_Call) Return(_a0 error) *MockBillTypeRepo_BulkDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillTypeRepo_BulkDelete_Call) RunAndReturn(run func(context.Context, []uint) error) *MockBillTypeRepo_BulkDelete_Call {
	_c.Call.Return(run)
	return _c
}

// BulkRestore provides a mock function with given fields: ctx, ids
func (_m *MockBillTypeRepo) BulkRestore(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkRestore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillTypeRepo_BulkRestore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkRestore'
type MockBillTypeRepo_BulkRestore_Call struct {
	*mock.Call
}

// BulkRestore is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint
func (_e *MockBillTypeRepo_Expecter) BulkRestore(ctx interface{}, ids interface{}) *MockBillTypeRepo_BulkRestore_Call {
	return &MockBillTypeRepo_BulkRestore_Call{Call: _e.mock.On("BulkRestore", ctx, ids)}
}

func (_c *MockBillTypeRepo_BulkRestore_Call) Run(run func(ctx context.Context, ids []uint)) *MockBillTypeRepo_BulkRestore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint))
	})
	return _c
}

func (_c *MockBillTypeRepo_BulkRestore_Call) Return(_a0 error) *MockBillTypeRepo_BulkRestore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillTypeRepo_BulkRestore_Call) RunAndReturn(run func(context.Context, []uint) error) *MockBillTypeRepo_BulkRestore_Call {
	_c.Call.Return(run)
	return _c
}

// CountBillingRules provides a mock function with given fields: ctx, billTypeID
func (_m *MockBillTypeRepo) CountBillingRules(ctx context.Context, billTypeID uint) (int, error) {
	ret := _m.Called(ctx, billTypeID)

	if len(ret) == 0 {
		panic("no return value specified for CountBillingRules")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int, error)); ok {
		return rf(ctx, billTypeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int); ok {
		r0 = rf(ctx, billTypeID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, billTypeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillTypeRepo_CountBillingRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountBillingRules'
type MockBillTypeRepo_CountBillingRules_Call struct {
	*mock.Call
}

// CountBillingRules is a helper method to define mock.On call
//   - ctx context.Context
//   - billTypeID uint
func (_e *MockBillTypeRepo_Expecter) CountBillingRules(ctx interface{}, billTypeID interface{}) *MockBillTypeRepo_CountBillingRules_Call {
	return &MockBillTypeRepo_CountBillingRules_Call{Call: _e.mock.On("CountBillingRules", ctx, billTypeID)}
}

func (_c *MockBillTypeRepo_CountBillingRules_Call) Run(run func(ctx context.Context, billTypeID uint)) *MockBillTypeRepo_CountBillingRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockBillTypeRepo_CountBillingRules_Call) Return(_a0 int, _a1 error) *MockBillTypeRepo_CountBillingRules_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillTypeRepo_CountBillingRules_Call) RunAndReturn(run func(context.Context, uint) (int, error)) *MockBillTypeRepo_CountBillingRules_Call {
	_c.Call.Return(run)
	return _c
}

// CountStudentBills provides a mock function with given fields: ctx, billTypeID
func (_m *MockBillTypeRepo) CountStudentBills(ctx context.Context, billTypeID uint) (int, error) {
	ret := _m.Called(ctx, billTypeID)

	if len(ret) == 0 {
		panic("no return value specified for CountStudentBills")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int, error)); ok {
		return rf(ctx, billTypeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int); ok {
		r0 = rf(ctx, billTypeID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, billTypeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillTypeRepo_CountStudentBills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountStudentBills'
type MockBillTypeRepo_CountStudentBills_Call struct {
	*mock.Call
}

// CountStudentBills is a helper method to define mock.On call
//   - ctx context.Context
//   - billTypeID uint
func (_e *MockBillTypeRepo_Expecter) CountStudentBills(ctx interface{}, billTypeID interface{}) *MockBillTypeRepo_CountStudentBills_Call {
	return &MockBillTypeRepo_CountStudentBills_Call{Call: _e.mock.On("CountStudentBills", ctx, billTypeID)}
}

func (_c *MockBillTypeRepo_CountStudentBills_Call) Run(run func(ctx context.Context, billTypeID uint)) *MockBillTypeRepo_CountStudentBills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockBillTypeRepo_CountStudentBills_Call) Return(_a0 int, _a1 error) *MockBillTypeRepo_CountStudentBills_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillTypeRepo_CountStudentBills_Call) RunAndReturn(run func(context.Context, uint) (int, error)) *MockBillTypeRepo_CountStudentBills_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, b
func (_m *MockBillTypeRepo) Create(ctx context.Context, b *domain.BillType) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BillType) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillTypeRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBillTypeRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - b *domain.BillType
func (_e *MockBillTypeRepo_Expecter) Create(ctx interface{}, b interface{}) *MockBillTypeRepo_Create_Call {
	return &MockBillTypeRepo_Create_Call{Call: _e.mock.On("Create", ctx, b)}
}

func (_c *MockBillTypeRepo_Create_Call) Run(run func(ctx context.Context, b *domain.BillType)) *MockBillTypeRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.BillType))
	})
	return _c
}

func (_c *MockBillTypeRepo_Create_Call) Return(_a0 error) *MockBillTypeRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillTypeRepo_Create_Call) RunAndReturn(run func(context.Context, *domain.BillType) error) *MockBillTypeRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockBillTypeRepo) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillTypeRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBillTypeRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockBillTypeRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockBillTypeRepo_Delete_Call {
	return &MockBillTypeRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockBillTypeRepo_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockBillTypeRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockBillTypeRepo_Delete_Call) Return(_a0 error) *MockBillTypeRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillTypeRepo_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockBillTypeRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, name
func (_m *MockBillTypeRepo) Exists(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillTypeRepo_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockBillTypeRepo_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockBillTypeRepo_Expecter) Exists(ctx interface{}, name interface{}) *MockBillTypeRepo_Exists_Call {
	return &MockBillTypeRepo_Exists_Call{Call: _e.mock.On("Exists", ctx, name)}
}

func (_c *MockBillTypeRepo_Exists_Call) Run(run func(ctx context.Context, name string)) *MockBillTypeRepo_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockBillTypeRepo_Exists_Call) Return(_a0 bool, _a1 error) *MockBillTypeRepo_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillTypeRepo_Exists_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockBillTypeRepo_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsExcludeID provides a mock function with given fields: ctx, name, id
func (_m *MockBillTypeRepo) ExistsExcludeID(ctx context.Context, name string, id uint) (bool, error) {
	ret := _m.Called(ctx, name, id)

	if len(ret) == 0 {
		panic("no return value specified for ExistsExcludeID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) (bool, error)); ok {
		return rf(ctx, name, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) bool); ok {
		r0 = rf(ctx, name, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = rf(ctx, name, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillTypeRepo_ExistsExcludeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsExcludeID'
type MockBillTypeRepo_ExistsExcludeID_Call struct {
	*mock.Call
}

// ExistsExcludeID is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - id uint
func (_e *MockBillTypeRepo_Expecter) ExistsExcludeID(ctx interface{}, name interface{}, id interface{}) *MockBillTypeRepo_ExistsExcludeID_Call {
	return &MockBillTypeRepo_ExistsExcludeID_Call{Call: _e.mock.On("ExistsExcludeID", ctx, name, id)}
}

func (_c *MockBillTypeRepo_ExistsExcludeID_Call) Run(run func(ctx context.Context, name string, id uint)) *MockBillTypeRepo_ExistsExcludeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uint))
	})
	return _c
}

func (_c *MockBillTypeRepo_ExistsExcludeID_Call) Return(_a0 bool, _a1 error) *MockBillTypeRepo_ExistsExcludeID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillTypeRepo_ExistsExcludeID_Call) RunAndReturn(run func(context.Context, string, uint) (bool, error)) *MockBillTypeRepo_ExistsExcludeID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockBillTypeRepo) FindAll(ctx context.Context) ([]domain.BillType, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.BillType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.BillType, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.BillType); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BillType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillTypeRepo_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockBillTypeRepo_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBillTypeRepo_Expecter) FindAll(ctx interface{}) *MockBillTypeRepo_FindAll_Call {
	return &MockBillTypeRepo_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockBillTypeRepo_FindAll_Call) Run(run func(ctx context.Context)) *MockBillTypeRepo_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBillTypeRepo_FindAll_Call) Return(_a0 []domain.BillType, _a1 error) *MockBillTypeRepo_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillTypeRepo_FindAll_Call) RunAndReturn(run func(context.Context) ([]domain.BillType, error)) *MockBillTypeRepo_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPaged provides a mock function with given fields: ctx, page, limit, search, filterType, status, sort
func (_m *MockBillTypeRepo) FindAllPaged(ctx context.Context, page int, limit int, search string, filterType string, status string, sort string) ([]domain.BillType, int, error) {
	ret := _m.Called(ctx, page, limit, search, filterType, status, sort)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaged")
	}

	var r0 []domain.BillType
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string) ([]domain.BillType, int, error)); ok {
		return rf(ctx, page, limit, search, filterType, status, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string) []domain.BillType); ok {
		r0 = rf(ctx, page, limit, search, filterType, status, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BillType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, string, string) int); ok {
		r1 = rf(ctx, page, limit, search, filterType, status, sort)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string, string, string) error); ok {
		r2 = rf(ctx, page, limit, search, filterType, status, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBillTypeRepo_FindAllPaged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPaged'
type MockBillTypeRepo_FindAllPaged_Call struct {
	*mock.Call
}

// FindAllPaged is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
//   - search string
//   - filterType string
//   - status string
//   - sort string
func (_e *MockBillTypeRepo_Expecter) FindAllPaged(ctx interface{}, page interface{}, limit interface{}, search interface{}, filterType interface{}, status interface{}, sort interface{}) *MockBillTypeRepo_FindAllPaged_Call {
	return &MockBillTypeRepo_FindAllPaged_Call{Call: _e.mock.On("FindAllPaged", ctx, page, limit, search, filterType, status, sort)}
}

func (_c *MockBillTypeRepo_FindAllPaged_Call) Run(run func(ctx context.Context, page int, limit int, search string, filterType string, status string, sort string)) *MockBillTypeRepo_FindAllPaged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(string), args[4].(string), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *MockBillTypeRepo_FindAllPaged_Call) Return(_a0 []domain.BillType, _a1 int, _a2 error) *MockBillTypeRepo_FindAllPaged_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBillTypeRepo_FindAllPaged_Call) RunAndReturn(run func(context.Context, int, int, string, string, string, string) ([]domain.BillType, int, error)) *MockBillTypeRepo_FindAllPaged_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockBillTypeRepo) FindByID(ctx context.Context, id uint) (*domain.BillType, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.BillType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.BillType, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.BillType); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BillType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillTypeRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBillTypeRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockBillTypeRepo_Expecter) FindByID(ctx interface{}, id interface{}) *MockBillTypeRepo_FindByID_Call {
	return &MockBillTypeRepo_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockBillTypeRepo_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockBillTypeRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockBillTypeRepo_FindByID_Call) Return(_a0 *domain.BillType, _a1 error) *MockBillTypeRepo_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillTypeRepo_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*domain.BillType, error)) *MockBillTypeRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function with given fields: ctx, id
func (_m *MockBillTypeRepo) Restore(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillTypeRepo_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockBillTypeRepo_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockBillTypeRepo_Expecter) Restore(ctx interface{}, id interface{}) *MockBillTypeRepo_Restore_Call {
	return &MockBillTypeRepo_Restore_Call{Call: _e.mock.On("Restore", ctx, id)}
}

func (_c *MockBillTypeRepo_Restore_Call) Run(run func(ctx context.Context, id uint)) *MockBillTypeRepo_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockBillTypeRepo_Restore_Call) Return(_a0 error) *MockBillTypeRepo_Restore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillTypeRepo_Restore_Call) RunAndReturn(run func(context.Context, uint) error) *MockBillTypeRepo_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleStatus provides a mock function with given fields: ctx, id
func (_m *MockBillTypeRepo) ToggleStatus(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ToggleStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillTypeRepo_ToggleStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleStatus'
type MockBillTypeRepo_ToggleStatus_Call struct {
	*mock.Call
}

// ToggleStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockBillTypeRepo_Expecter) ToggleStatus(ctx interface{}, id interface{}) *MockBillTypeRepo_ToggleStatus_Call {
	return &MockBillTypeRepo_ToggleStatus_Call{Call: _e.mock.On("ToggleStatus", ctx, id)}
}

func (_c *MockBillTypeRepo_ToggleStatus_Call) Run(run func(ctx context.Context, id uint)) *MockBillTypeRepo_ToggleStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockBillTypeRepo_ToggleStatus_Call) Return(_a0 error) *MockBillTypeRepo_ToggleStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillTypeRepo_ToggleStatus_Call) RunAndReturn(run func(context.Context, uint) error) *MockBillTypeRepo_ToggleStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, b
func (_m *MockBillTypeRepo) Update(ctx context.Context, b *domain.BillType) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BillType) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillTypeRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBillTypeRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - b *domain.BillType
func (_e *MockBillTypeRepo_Expecter) Update(ctx interface{}, b interface{}) *MockBillTypeRepo_Update_Call {
	return &MockBillTypeRepo_Update_Call{Call: _e.mock.On("Update", ctx, b)}
}

func (_c *MockBillTypeRepo_Update_Call) Run(run func(ctx context.Context, b *domain.BillType)) *MockBillTypeRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.BillType))
	})
	return _c
}

func (_c *MockBillTypeRepo_Update_Call) Return(_a0 error) *MockBillTypeRepo_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillTypeRepo_Update_Call) RunAndReturn(run func(context.Context, *domain.BillType) error) *MockBillTypeRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBillTypeRepo creates a new instance of MockBillTypeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBillTypeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBillTypeRepo {
	mock := &MockBillTypeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
