// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/finance/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockBillingRuleRepo is an autogenerated mock type for the BillingRuleRepo type
type MockBillingRuleRepo struct {
	mock.Mock
}

type MockBillingRuleRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBillingRuleRepo) EXPECT() *MockBillingRuleRepo_Expecter {
	return &MockBillingRuleRepo_Expecter{mock: &_m.Mock}
}

// BulkDelete provides a mock function with given fields: ctx, ids
func (_m *MockBillingRuleRepo) BulkDelete(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillingRuleRepo_BulkDelete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkDelete'
type MockBillingRuleRepo_BulkDelete_Call struct {
	*mock.Call
}

// BulkDelete is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint
func (_e *MockBillingRuleRepo_Expecter) BulkDelete(ctx interface{}, ids interface{}) *MockBillingRuleRepo_BulkDelete_Call {
	return &MockBillingRuleRepo_BulkDelete_Call{Call: _e.mock.On("BulkDelete", ctx, ids)}
}

func (_c *MockBillingRuleRepo_BulkDelete_Call) Run(run func(ctx context.Context, ids []uint)) *MockBillingRuleRepo_BulkDelete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint))
	})
	return _c
}

func (_c *MockBillingRuleRepo_BulkDelete_Call) Return(_a0 error) *MockBillingRuleRepo_BulkDelete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillingRuleRepo_BulkDelete_Call) RunAndReturn(run func(context.Context, []uint) error) *MockBillingRuleRepo_BulkDelete_Call {
	_c.Call.Return(run)
	return _c
}

// BulkRestore provides a mock function with given fields: ctx, ids
func (_m *MockBillingRuleRepo) BulkRestore(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkRestore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillingRuleRepo_BulkRestore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkRestore'
type MockBillingRuleRepo_BulkRestore_Call struct {
	*mock.Call
}

// BulkRestore is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uint
func (_e *MockBillingRuleRepo_Expecter) BulkRestore(ctx interface{}, ids interface{}) *MockBillingRuleRepo_BulkRestore_Call {
	return &MockBillingRuleRepo_BulkRestore_Call{Call: _e.mock.On("BulkRestore", ctx, ids)}
}

func (_c *MockBillingRuleRepo_BulkRestore_Call) Run(run func(ctx context.Context, ids []uint)) *MockBillingRuleRepo_BulkRestore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]uint))
	})
	return _c
}

func (_c *MockBillingRuleRepo_BulkRestore_Call) Return(_a0 error) *MockBillingRuleRepo_BulkRestore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillingRuleRepo_BulkRestore_Call) RunAndReturn(run func(context.Context, []uint) error) *MockBillingRuleRepo_BulkRestore_Call {
	_c.Call.Return(run)
	return _c
}

// CountStudentBills provides a mock function with given fields: ctx, ruleID
func (_m *MockBillingRuleRepo) CountStudentBills(ctx context.Context, ruleID uint) (int, error) {
	ret := _m.Called(ctx, ruleID)

	if len(ret) == 0 {
		panic("no return value specified for CountStudentBills")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int, error)); ok {
		return rf(ctx, ruleID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int); ok {
		r0 = rf(ctx, ruleID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, ruleID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillingRuleRepo_CountStudentBills_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountStudentBills'
type MockBillingRuleRepo_CountStudentBills_Call struct {
	*mock.Call
}

// CountStudentBills is a helper method to define mock.On call
//   - ctx context.Context
//   - ruleID uint
func (_e *MockBillingRuleRepo_Expecter) CountStudentBills(ctx interface{}, ruleID interface{}) *MockBillingRuleRepo_CountStudentBills_Call {
	return &MockBillingRuleRepo_CountStudentBills_Call{Call: _e.mock.On("CountStudentBills", ctx, ruleID)}
}

func (_c *MockBillingRuleRepo_CountStudentBills_Call) Run(run func(ctx context.Context, ruleID uint)) *MockBillingRuleRepo_CountStudentBills_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockBillingRuleRepo_CountStudentBills_Call) Return(_a0 int, _a1 error) *MockBillingRuleRepo_CountStudentBills_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillingRuleRepo_CountStudentBills_Call) RunAndReturn(run func(context.Context, uint) (int, error)) *MockBillingRuleRepo_CountStudentBills_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, br
func (_m *MockBillingRuleRepo) Create(ctx context.Context, br *domain.BillingRule) error {
	ret := _m.Called(ctx, br)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BillingRule) error); ok {
		r0 = rf(ctx, br)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillingRuleRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBillingRuleRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - br *domain.BillingRule
func (_e *MockBillingRuleRepo_Expecter) Create(ctx interface{}, br interface{}) *MockBillingRuleRepo_Create_Call {
	return &MockBillingRuleRepo_Create_Call{Call: _e.mock.On("Create", ctx, br)}
}

func (_c *MockBillingRuleRepo_Create_Call) Run(run func(ctx context.Context, br *domain.BillingRule)) *MockBillingRuleRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.BillingRule))
	})
	return _c
}

func (_c *MockBillingRuleRepo_Create_Call) Return(_a0 error) *MockBillingRuleRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillingRuleRepo_Create_Call) RunAndReturn(run func(context.Context, *domain.BillingRule) error) *MockBillingRuleRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockBillingRuleRepo) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillingRuleRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBillingRuleRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockBillingRuleRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockBillingRuleRepo_Delete_Call {
	return &MockBillingRuleRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockBillingRuleRepo_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockBillingRuleRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockBillingRuleRepo_Delete_Call) Return(_a0 error) *MockBillingRuleRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillingRuleRepo_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockBillingRuleRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function with given fields: ctx, btID, targetType, targetID, classID
func (_m *MockBillingRuleRepo) Exists(ctx context.Context, btID uint, targetType string, targetID uint, classID *uint) (bool, error) {
	ret := _m.Called(ctx, btID, targetType, targetID, classID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, uint, *uint) (bool, error)); ok {
		return rf(ctx, btID, targetType, targetID, classID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, uint, *uint) bool); ok {
		r0 = rf(ctx, btID, targetType, targetID, classID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string, uint, *uint) error); ok {
		r1 = rf(ctx, btID, targetType, targetID, classID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillingRuleRepo_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockBillingRuleRepo_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - btID uint
//   - targetType string
//   - targetID uint
//   - classID *uint
func (_e *MockBillingRuleRepo_Expecter) Exists(ctx interface{}, btID interface{}, targetType interface{}, targetID interface{}, classID interface{}) *MockBillingRuleRepo_Exists_Call {
	return &MockBillingRuleRepo_Exists_Call{Call: _e.mock.On("Exists", ctx, btID, targetType, targetID, classID)}
}

func (_c *MockBillingRuleRepo_Exists_Call) Run(run func(ctx context.Context, btID uint, targetType string, targetID uint, classID *uint)) *MockBillingRuleRepo_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(uint), args[4].(*uint))
	})
	return _c
}

func (_c *MockBillingRuleRepo_Exists_Call) Return(_a0 bool, _a1 error) *MockBillingRuleRepo_Exists_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillingRuleRepo_Exists_Call) RunAndReturn(run func(context.Context, uint, string, uint, *uint) (bool, error)) *MockBillingRuleRepo_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsExcludeID provides a mock function with given fields: ctx, btID, targetType, targetID, classID, excludeID
func (_m *MockBillingRuleRepo) ExistsExcludeID(ctx context.Context, btID uint, targetType string, targetID uint, classID *uint, excludeID uint) (bool, error) {
	ret := _m.Called(ctx, btID, targetType, targetID, classID, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsExcludeID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, uint, *uint, uint) (bool, error)); ok {
		return rf(ctx, btID, targetType, targetID, classID, excludeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, uint, *uint, uint) bool); ok {
		r0 = rf(ctx, btID, targetType, targetID, classID, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string, uint, *uint, uint) error); ok {
		r1 = rf(ctx, btID, targetType, targetID, classID, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillingRuleRepo_ExistsExcludeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsExcludeID'
type MockBillingRuleRepo_ExistsExcludeID_Call struct {
	*mock.Call
}

// ExistsExcludeID is a helper method to define mock.On call
//   - ctx context.Context
//   - btID uint
//   - targetType string
//   - targetID uint
//   - classID *uint
//   - excludeID uint
func (_e *MockBillingRuleRepo_Expecter) ExistsExcludeID(ctx interface{}, btID interface{}, targetType interface{}, targetID interface{}, classID interface{}, excludeID interface{}) *MockBillingRuleRepo_ExistsExcludeID_Call {
	return &MockBillingRuleRepo_ExistsExcludeID_Call{Call: _e.mock.On("ExistsExcludeID", ctx, btID, targetType, targetID, classID, excludeID)}
}

func (_c *MockBillingRuleRepo_ExistsExcludeID_Call) Run(run func(ctx context.Context, btID uint, targetType string, targetID uint, classID *uint, excludeID uint)) *MockBillingRuleRepo_ExistsExcludeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(string), args[3].(uint), args[4].(*uint), args[5].(uint))
	})
	return _c
}

func (_c *MockBillingRuleRepo_ExistsExcludeID_Call) Return(_a0 bool, _a1 error) *MockBillingRuleRepo_ExistsExcludeID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillingRuleRepo_ExistsExcludeID_Call) RunAndReturn(run func(context.Context, uint, string, uint, *uint, uint) (bool, error)) *MockBillingRuleRepo_ExistsExcludeID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx
func (_m *MockBillingRuleRepo) FindAll(ctx context.Context) ([]domain.BillingRule, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.BillingRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.BillingRule, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.BillingRule); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BillingRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillingRuleRepo_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockBillingRuleRepo_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBillingRuleRepo_Expecter) FindAll(ctx interface{}) *MockBillingRuleRepo_FindAll_Call {
	return &MockBillingRuleRepo_FindAll_Call{Call: _e.mock.On("FindAll", ctx)}
}

func (_c *MockBillingRuleRepo_FindAll_Call) Run(run func(ctx context.Context)) *MockBillingRuleRepo_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockBillingRuleRepo_FindAll_Call) Return(_a0 []domain.BillingRule, _a1 error) *MockBillingRuleRepo_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillingRuleRepo_FindAll_Call) RunAndReturn(run func(context.Context) ([]domain.BillingRule, error)) *MockBillingRuleRepo_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindAllPaged provides a mock function with given fields: ctx, page, limit, search, status, generateStatus, sort
func (_m *MockBillingRuleRepo) FindAllPaged(ctx context.Context, page int, limit int, search string, status string, generateStatus string, sort string) ([]domain.BillingRule, int, error) {
	ret := _m.Called(ctx, page, limit, search, status, generateStatus, sort)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaged")
	}

	var r0 []domain.BillingRule
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string) ([]domain.BillingRule, int, error)); ok {
		return rf(ctx, page, limit, search, status, generateStatus, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string) []domain.BillingRule); ok {
		r0 = rf(ctx, page, limit, search, status, generateStatus, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BillingRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, string, string) int); ok {
		r1 = rf(ctx, page, limit, search, status, generateStatus, sort)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string, string, string) error); ok {
		r2 = rf(ctx, page, limit, search, status, generateStatus, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockBillingRuleRepo_FindAllPaged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAllPaged'
type MockBillingRuleRepo_FindAllPaged_Call struct {
	*mock.Call
}

// FindAllPaged is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - limit int
//   - search string
//   - status string
//   - generateStatus string
//   - sort string
func (_e *MockBillingRuleRepo_Expecter) FindAllPaged(ctx interface{}, page interface{}, limit interface{}, search interface{}, status interface{}, generateStatus interface{}, sort interface{}) *MockBillingRuleRepo_FindAllPaged_Call {
	return &MockBillingRuleRepo_FindAllPaged_Call{Call: _e.mock.On("FindAllPaged", ctx, page, limit, search, status, generateStatus, sort)}
}

func (_c *MockBillingRuleRepo_FindAllPaged_Call) Run(run func(ctx context.Context, page int, limit int, search string, status string, generateStatus string, sort string)) *MockBillingRuleRepo_FindAllPaged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int), args[3].(string), args[4].(string), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *MockBillingRuleRepo_FindAllPaged_Call) Return(_a0 []domain.BillingRule, _a1 int, _a2 error) *MockBillingRuleRepo_FindAllPaged_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockBillingRuleRepo_FindAllPaged_Call) RunAndReturn(run func(context.Context, int, int, string, string, string, string) ([]domain.BillingRule, int, error)) *MockBillingRuleRepo_FindAllPaged_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockBillingRuleRepo) FindByID(ctx context.Context, id uint) (*domain.BillingRule, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.BillingRule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.BillingRule, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.BillingRule); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BillingRule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBillingRuleRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockBillingRuleRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockBillingRuleRepo_Expecter) FindByID(ctx interface{}, id interface{}) *MockBillingRuleRepo_FindByID_Call {
	return &MockBillingRuleRepo_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockBillingRuleRepo_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockBillingRuleRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockBillingRuleRepo_FindByID_Call) Return(_a0 *domain.BillingRule, _a1 error) *MockBillingRuleRepo_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBillingRuleRepo_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*domain.BillingRule, error)) *MockBillingRuleRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// Restore provides a mock function with given fields: ctx, id
func (_m *MockBillingRuleRepo) Restore(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillingRuleRepo_Restore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Restore'
type MockBillingRuleRepo_Restore_Call struct {
	*mock.Call
}

// Restore is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockBillingRuleRepo_Expecter) Restore(ctx interface{}, id interface{}) *MockBillingRuleRepo_Restore_Call {
	return &MockBillingRuleRepo_Restore_Call{Call: _e.mock.On("Restore", ctx, id)}
}

func (_c *MockBillingRuleRepo_Restore_Call) Run(run func(ctx context.Context, id uint)) *MockBillingRuleRepo_Restore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockBillingRuleRepo_Restore_Call) Return(_a0 error) *MockBillingRuleRepo_Restore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillingRuleRepo_Restore_Call) RunAndReturn(run func(context.Context, uint) error) *MockBillingRuleRepo_Restore_Call {
	_c.Call.Return(run)
	return _c
}

// ToggleStatus provides a mock function with given fields: ctx, id
func (_m *MockBillingRuleRepo) ToggleStatus(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ToggleStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillingRuleRepo_ToggleStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToggleStatus'
type MockBillingRuleRepo_ToggleStatus_Call struct {
	*mock.Call
}

// ToggleStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockBillingRuleRepo_Expecter) ToggleStatus(ctx interface{}, id interface{}) *MockBillingRuleRepo_ToggleStatus_Call {
	return &MockBillingRuleRepo_ToggleStatus_Call{Call: _e.mock.On("ToggleStatus", ctx, id)}
}

func (_c *MockBillingRuleRepo_ToggleStatus_Call) Run(run func(ctx context.Context, id uint)) *MockBillingRuleRepo_ToggleStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockBillingRuleRepo_ToggleStatus_Call) Return(_a0 error) *MockBillingRuleRepo_ToggleStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillingRuleRepo_ToggleStatus_Call) RunAndReturn(run func(context.Context, uint) error) *MockBillingRuleRepo_ToggleStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, br
func (_m *MockBillingRuleRepo) Update(ctx context.Context, br *domain.BillingRule) error {
	ret := _m.Called(ctx, br)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BillingRule) error); ok {
		r0 = rf(ctx, br)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBillingRuleRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBillingRuleRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - br *domain.BillingRule
func (_e *MockBillingRuleRepo_Expecter) Update(ctx interface{}, br interface{}) *MockBillingRuleRepo_Update_Call {
	return &MockBillingRuleRepo_Update_Call{Call: _e.mock.On("Update", ctx, br)}
}

func (_c *MockBillingRuleRepo_Update_Call) Run(run func(ctx context.Context, br *domain.BillingRule)) *MockBillingRuleRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.BillingRule))
	})
	return _c
}

func (_c *MockBillingRuleRepo_Update_Call) Return(_a0 error) *MockBillingRuleRepo_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBillingRuleRepo_Update_Call) RunAndReturn(run func(context.Context, *domain.BillingRule) error) *MockBillingRuleRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBillingRuleRepo creates a new instance of MockBillingRuleRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBillingRuleRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBillingRuleRepo {
	mock := &MockBillingRuleRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
