// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/finance/domain"
	mock "github.com/stretchr/testify/mock"
)

// BillTypeRepo is an autogenerated mock type for the BillTypeRepo type
type BillTypeRepo struct {
	mock.Mock
}

// BulkDelete provides a mock function with given fields: ctx, ids
func (_m *BillTypeRepo) BulkDelete(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BulkRestore provides a mock function with given fields: ctx, ids
func (_m *BillTypeRepo) BulkRestore(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkRestore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountBillingRules provides a mock function with given fields: ctx, billTypeID
func (_m *BillTypeRepo) CountBillingRules(ctx context.Context, billTypeID uint) (int, error) {
	ret := _m.Called(ctx, billTypeID)

	if len(ret) == 0 {
		panic("no return value specified for CountBillingRules")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int, error)); ok {
		return rf(ctx, billTypeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int); ok {
		r0 = rf(ctx, billTypeID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, billTypeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountStudentBills provides a mock function with given fields: ctx, billTypeID
func (_m *BillTypeRepo) CountStudentBills(ctx context.Context, billTypeID uint) (int, error) {
	ret := _m.Called(ctx, billTypeID)

	if len(ret) == 0 {
		panic("no return value specified for CountStudentBills")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int, error)); ok {
		return rf(ctx, billTypeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int); ok {
		r0 = rf(ctx, billTypeID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, billTypeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, b
func (_m *BillTypeRepo) Create(ctx context.Context, b *domain.BillType) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BillType) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *BillTypeRepo) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, name
func (_m *BillTypeRepo) Exists(ctx context.Context, name string) (bool, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExistsExcludeID provides a mock function with given fields: ctx, name, id
func (_m *BillTypeRepo) ExistsExcludeID(ctx context.Context, name string, id uint) (bool, error) {
	ret := _m.Called(ctx, name, id)

	if len(ret) == 0 {
		panic("no return value specified for ExistsExcludeID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) (bool, error)); ok {
		return rf(ctx, name, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) bool); ok {
		r0 = rf(ctx, name, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = rf(ctx, name, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx
func (_m *BillTypeRepo) FindAll(ctx context.Context) ([]domain.BillType, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.BillType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.BillType, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.BillType); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BillType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllPaged provides a mock function with given fields: ctx, page, limit, search, filterType, status, sort
func (_m *BillTypeRepo) FindAllPaged(ctx context.Context, page int, limit int, search string, filterType string, status string, sort string) ([]domain.BillType, int, error) {
	ret := _m.Called(ctx, page, limit, search, filterType, status, sort)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaged")
	}

	var r0 []domain.BillType
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string) ([]domain.BillType, int, error)); ok {
		return rf(ctx, page, limit, search, filterType, status, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string) []domain.BillType); ok {
		r0 = rf(ctx, page, limit, search, filterType, status, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BillType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, string, string) int); ok {
		r1 = rf(ctx, page, limit, search, filterType, status, sort)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string, string, string) error); ok {
		r2 = rf(ctx, page, limit, search, filterType, status, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *BillTypeRepo) FindByID(ctx context.Context, id uint) (*domain.BillType, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.BillType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.BillType, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.BillType); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BillType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Restore provides a mock function with given fields: ctx, id
func (_m *BillTypeRepo) Restore(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ToggleStatus provides a mock function with given fields: ctx, id
func (_m *BillTypeRepo) ToggleStatus(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ToggleStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, b
func (_m *BillTypeRepo) Update(ctx context.Context, b *domain.BillType) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BillType) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBillTypeRepo creates a new instance of BillTypeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBillTypeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *BillTypeRepo {
	mock := &BillTypeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
