// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/finance/domain"
	mock "github.com/stretchr/testify/mock"
)

// BillTypeService is an autogenerated mock type for the BillTypeService type
type BillTypeService struct {
	mock.Mock
}

// BulkDelete provides a mock function with given fields: ctx, ids
func (_m *BillTypeService) BulkDelete(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BulkRestore provides a mock function with given fields: ctx, ids
func (_m *BillTypeService) BulkRestore(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkRestore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, b
func (_m *BillTypeService) Create(ctx context.Context, b *domain.BillType) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BillType) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *BillTypeService) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx
func (_m *BillTypeService) GetAll(ctx context.Context) ([]domain.BillType, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.BillType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.BillType, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.BillType); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BillType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllPaged provides a mock function with given fields: ctx, page, limit, search, filterType, status, sort
func (_m *BillTypeService) GetAllPaged(ctx context.Context, page int, limit int, search string, filterType string, status string, sort string) ([]domain.BillType, int, error) {
	ret := _m.Called(ctx, page, limit, search, filterType, status, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPaged")
	}

	var r0 []domain.BillType
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string) ([]domain.BillType, int, error)); ok {
		return rf(ctx, page, limit, search, filterType, status, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string) []domain.BillType); ok {
		r0 = rf(ctx, page, limit, search, filterType, status, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.BillType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, string, string) int); ok {
		r1 = rf(ctx, page, limit, search, filterType, status, sort)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string, string, string) error); ok {
		r2 = rf(ctx, page, limit, search, filterType, status, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *BillTypeService) GetByID(ctx context.Context, id uint) (*domain.BillType, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.BillType
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.BillType, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.BillType); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.BillType)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDependencyInfo provides a mock function with given fields: ctx, id
func (_m *BillTypeService) GetDependencyInfo(ctx context.Context, id uint) (map[string]interface{}, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDependencyInfo")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (map[string]interface{}, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) map[string]interface{}); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Restore provides a mock function with given fields: ctx, id
func (_m *BillTypeService) Restore(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ToggleStatus provides a mock function with given fields: ctx, id
func (_m *BillTypeService) ToggleStatus(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ToggleStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, b
func (_m *BillTypeService) Update(ctx context.Context, b *domain.BillType) error {
	ret := _m.Called(ctx, b)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.BillType) error); ok {
		r0 = rf(ctx, b)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckUnique provides a mock function with given fields: ctx, name, excludeID
func (_m *BillTypeService) CheckUnique(ctx context.Context, name string, excludeID uint) (bool, error) {
	ret := _m.Called(ctx, name, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for CheckUnique")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) bool); ok {
		r0 = rf(ctx, name, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = rf(ctx, name, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBillTypeService creates a new instance of BillTypeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBillTypeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BillTypeService {
	mock := &BillTypeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
