// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/academic/domain"
	mock "github.com/stretchr/testify/mock"
)

// ClassRepo is an autogenerated mock type for the ClassRepo type
type ClassRepo struct {
	mock.Mock
}

// BulkDelete provides a mock function with given fields: ctx, ids
func (_m *ClassRepo) BulkDelete(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BulkRestore provides a mock function with given fields: ctx, ids
func (_m *ClassRepo) BulkRestore(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkRestore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountAcademicYears provides a mock function with given fields: ctx, classID
func (_m *ClassRepo) CountAcademicYears(ctx context.Context, classID uint) (int, error) {
	ret := _m.Called(ctx, classID)

	if len(ret) == 0 {
		panic("no return value specified for CountAcademicYears")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int, error)); ok {
		return rf(ctx, classID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int); ok {
		r0 = rf(ctx, classID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, classID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountStudents provides a mock function with given fields: ctx, classID
func (_m *ClassRepo) CountStudents(ctx context.Context, classID uint) (int, error) {
	ret := _m.Called(ctx, classID)

	if len(ret) == 0 {
		panic("no return value specified for CountStudents")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int, error)); ok {
		return rf(ctx, classID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int); ok {
		r0 = rf(ctx, classID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, classID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, c
func (_m *ClassRepo) Create(ctx context.Context, c *domain.Class) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Class) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ClassRepo) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, name, ayID, majorID, excludeID
func (_m *ClassRepo) Exists(ctx context.Context, name string, ayID uint, majorID uint, excludeID uint) (bool, error) {
	ret := _m.Called(ctx, name, ayID, majorID, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, uint, uint) (bool, error)); ok {
		return rf(ctx, name, ayID, majorID, excludeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, uint, uint) bool); ok {
		r0 = rf(ctx, name, ayID, majorID, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint, uint, uint) error); ok {
		r1 = rf(ctx, name, ayID, majorID, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx, page, limit, search, status, majorID, ayID
func (_m *ClassRepo) FindAll(ctx context.Context, page int, limit int, search string, status string, majorID string, ayID string, sort string) ([]domain.Class, int, error) {
	ret := _m.Called(ctx, page, limit, search, status, majorID, ayID, sort)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Class
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string, string) ([]domain.Class, int, error)); ok {
		return rf(ctx, page, limit, search, status, majorID, ayID, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string, string) []domain.Class); ok {
		r0 = rf(ctx, page, limit, search, status, majorID, ayID, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Class)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, string, string, string) int); ok {
		r1 = rf(ctx, page, limit, search, status, majorID, ayID, sort)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string, string, string, string) error); ok {
		r2 = rf(ctx, page, limit, search, status, majorID, ayID, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *ClassRepo) FindByID(ctx context.Context, id uint) (*domain.Class, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Class
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Class, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Class); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *ClassRepo) FindByName(ctx context.Context, name string) (*domain.Class, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *domain.Class
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Class, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Class); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Restore provides a mock function with given fields: ctx, id
func (_m *ClassRepo) Restore(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ToggleStatus provides a mock function with given fields: ctx, id
func (_m *ClassRepo) ToggleStatus(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ToggleStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, c
func (_m *ClassRepo) Update(ctx context.Context, c *domain.Class) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Class) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClassRepo creates a new instance of ClassRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClassRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClassRepo {
	mock := &ClassRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
