// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/academic/domain"
	mock "github.com/stretchr/testify/mock"
)

// ClassService is an autogenerated mock type for the ClassService type
type ClassService struct {
	mock.Mock
}

// BulkDelete provides a mock function with given fields: ctx, ids
func (_m *ClassService) BulkDelete(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BulkRestore provides a mock function with given fields: ctx, ids
func (_m *ClassService) BulkRestore(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkRestore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, c
func (_m *ClassService) Create(ctx context.Context, c *domain.Class) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Class) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ClassService) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, page, limit, search, status, majorID, ayID
func (_m *ClassService) GetAll(ctx context.Context, page int, limit int, search string, status string, majorID string, ayID string, sort string) ([]domain.Class, int, error) {
	ret := _m.Called(ctx, page, limit, search, status, majorID, ayID, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Class
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string, string) ([]domain.Class, int, error)); ok {
		return rf(ctx, page, limit, search, status, majorID, ayID, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string, string) []domain.Class); ok {
		r0 = rf(ctx, page, limit, search, status, majorID, ayID, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Class)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, string, string, string) int); ok {
		r1 = rf(ctx, page, limit, search, status, majorID, ayID, sort)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string, string, string, string) error); ok {
		r2 = rf(ctx, page, limit, search, status, majorID, ayID, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ClassService) GetByID(ctx context.Context, id uint) (*domain.Class, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Class
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Class, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Class); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Class)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDependencyInfo provides a mock function with given fields: ctx, id
func (_m *ClassService) GetDependencyInfo(ctx context.Context, id uint) (map[string]interface{}, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDependencyInfo")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (map[string]interface{}, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) map[string]interface{}); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Restore provides a mock function with given fields: ctx, id
func (_m *ClassService) Restore(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SuggestNextName provides a mock function with given fields: ctx, name, ayID, majorID, excludeID
func (_m *ClassService) SuggestNextName(ctx context.Context, name string, ayID uint, majorID uint, excludeID uint) (string, error) {
	ret := _m.Called(ctx, name, ayID, majorID, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for SuggestNextName")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, uint, uint) (string, error)); ok {
		return rf(ctx, name, ayID, majorID, excludeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, uint, uint) string); ok {
		r0 = rf(ctx, name, ayID, majorID, excludeID)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint, uint, uint) error); ok {
		r1 = rf(ctx, name, ayID, majorID, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ToggleStatus provides a mock function with given fields: ctx, id
func (_m *ClassService) ToggleStatus(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ToggleStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, c
func (_m *ClassService) Update(ctx context.Context, c *domain.Class) error {
	ret := _m.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Class) error); ok {
		r0 = rf(ctx, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CheckUnique provides a mock function with given fields: ctx, name, majorID, ayID, excludeID
func (_m *ClassService) CheckUnique(ctx context.Context, name string, majorID uint, ayID uint, excludeID uint) (bool, error) {
	ret := _m.Called(ctx, name, majorID, ayID, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for CheckUnique")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint, uint, uint) bool); ok {
		r0 = rf(ctx, name, majorID, ayID, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint, uint, uint) error); ok {
		r1 = rf(ctx, name, majorID, ayID, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClassService creates a new instance of ClassService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClassService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClassService {
	mock := &ClassService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
