// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bun "github.com/uptrace/bun"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/finance/domain"
	mock "github.com/stretchr/testify/mock"
)

// DepositMovementRepo is an autogenerated mock type for the DepositMovementRepo type
type DepositMovementRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, db, dm
func (_m *DepositMovementRepo) Create(ctx context.Context, db bun.IDB, dm *domain.DepositMovement) error {
	ret := _m.Called(ctx, db, dm)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *domain.DepositMovement) error); ok {
		r0 = rf(ctx, db, dm)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByStudent provides a mock function with given fields: ctx, studentID
func (_m *DepositMovementRepo) FindByStudent(ctx context.Context, studentID uint) ([]domain.DepositMovement, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for FindByStudent")
	}

	var r0 []domain.DepositMovement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.DepositMovement, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.DepositMovement); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.DepositMovement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDepositMovementRepo creates a new instance of DepositMovementRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDepositMovementRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *DepositMovementRepo {
	mock := &DepositMovementRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
