// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	usecase "github.com/ahmadzakyarifin/schoolpay/internal/module/notification/usecase"
	mock "github.com/stretchr/testify/mock"
)

// FinanceNotificationService is an autogenerated mock type for the FinanceNotificationService type
type FinanceNotificationService struct {
	mock.Mock
}

// Notify provides a mock function with given fields: job
func (_m *FinanceNotificationService) Notify(job usecase.FinanceNotifyJob) {
	_m.Called(job)
}

// NewFinanceNotificationService creates a new instance of FinanceNotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinanceNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FinanceNotificationService {
	mock := &FinanceNotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
