// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/finance/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// FinanceReportRepo is an autogenerated mock type for the FinanceReportRepo type
type FinanceReportRepo struct {
	mock.Mock
}

// GetArrearsPaged provides a mock function with given fields: ctx, page, limit, academicYear, classID, majorID, billTypeID, search, start, end
func (_m *FinanceReportRepo) GetArrearsPaged(ctx context.Context, page int, limit int, academicYear int, classID uint, majorID uint, billTypeID uint, search string, start *time.Time, end *time.Time) ([]domain.ArrearRecord, int, error) {
	ret := _m.Called(ctx, page, limit, academicYear, classID, majorID, billTypeID, search, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetArrearsPaged")
	}

	var r0 []domain.ArrearRecord
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, uint, uint, uint, string, *time.Time, *time.Time) ([]domain.ArrearRecord, int, error)); ok {
		return rf(ctx, page, limit, academicYear, classID, majorID, billTypeID, search, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, uint, uint, uint, string, *time.Time, *time.Time) []domain.ArrearRecord); ok {
		r0 = rf(ctx, page, limit, academicYear, classID, majorID, billTypeID, search, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ArrearRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int, uint, uint, uint, string, *time.Time, *time.Time) int); ok {
		r1 = rf(ctx, page, limit, academicYear, classID, majorID, billTypeID, search, start, end)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, int, uint, uint, uint, string, *time.Time, *time.Time) error); ok {
		r2 = rf(ctx, page, limit, academicYear, classID, majorID, billTypeID, search, start, end)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetCriticalBills provides a mock function with given fields: ctx, status, limit, academicYear, classID, majorID, billTypeID
func (_m *FinanceReportRepo) GetCriticalBills(ctx context.Context, status string, limit int, academicYear int, classID uint, majorID uint, billTypeID uint) ([]domain.CriticalBillRecord, error) {
	ret := _m.Called(ctx, status, limit, academicYear, classID, majorID, billTypeID)

	if len(ret) == 0 {
		panic("no return value specified for GetCriticalBills")
	}

	var r0 []domain.CriticalBillRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, uint, uint, uint) ([]domain.CriticalBillRecord, error)); ok {
		return rf(ctx, status, limit, academicYear, classID, majorID, billTypeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int, uint, uint, uint) []domain.CriticalBillRecord); ok {
		r0 = rf(ctx, status, limit, academicYear, classID, majorID, billTypeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.CriticalBillRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int, uint, uint, uint) error); ok {
		r1 = rf(ctx, status, limit, academicYear, classID, majorID, billTypeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDashboardSummary provides a mock function with given fields: ctx, start, end, academicYear, classID, majorID
func (_m *FinanceReportRepo) GetDashboardSummary(ctx context.Context, start *time.Time, end *time.Time, academicYear int, classID uint, majorID uint) (map[string]interface{}, error) {
	ret := _m.Called(ctx, start, end, academicYear, classID, majorID)

	if len(ret) == 0 {
		panic("no return value specified for GetDashboardSummary")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, uint, uint) (map[string]interface{}, error)); ok {
		return rf(ctx, start, end, academicYear, classID, majorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, uint, uint) map[string]interface{}); ok {
		r0 = rf(ctx, start, end, academicYear, classID, majorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *time.Time, *time.Time, int, uint, uint) error); ok {
		r1 = rf(ctx, start, end, academicYear, classID, majorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentMethodsCount provides a mock function with given fields: ctx, start, end, academicYear, classID, majorID
func (_m *FinanceReportRepo) GetPaymentMethodsCount(ctx context.Context, start *time.Time, end *time.Time, academicYear int, classID uint, majorID uint) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, start, end, academicYear, classID, majorID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentMethodsCount")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, uint, uint) ([]map[string]interface{}, error)); ok {
		return rf(ctx, start, end, academicYear, classID, majorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, uint, uint) []map[string]interface{}); ok {
		r0 = rf(ctx, start, end, academicYear, classID, majorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *time.Time, *time.Time, int, uint, uint) error); ok {
		r1 = rf(ctx, start, end, academicYear, classID, majorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaymentTrendByPeriod provides a mock function with given fields: ctx, start, end, interval, academicYear, classID, majorID
func (_m *FinanceReportRepo) GetPaymentTrendByPeriod(ctx context.Context, start *time.Time, end *time.Time, interval string, academicYear int, classID uint, majorID uint) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, start, end, interval, academicYear, classID, majorID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentTrendByPeriod")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, string, int, uint, uint) ([]map[string]interface{}, error)); ok {
		return rf(ctx, start, end, interval, academicYear, classID, majorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, string, int, uint, uint) []map[string]interface{}); ok {
		r0 = rf(ctx, start, end, interval, academicYear, classID, majorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *time.Time, *time.Time, string, int, uint, uint) error); ok {
		r1 = rf(ctx, start, end, interval, academicYear, classID, majorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRecentPayments provides a mock function with given fields: ctx, start, end, academicYear, classID, majorID, billTypeID, search, page, limit
func (_m *FinanceReportRepo) GetRecentPayments(ctx context.Context, start *time.Time, end *time.Time, academicYear int, classID uint, majorID uint, billTypeID uint, search string, page int, limit int) ([]map[string]interface{}, int, error) {
	ret := _m.Called(ctx, start, end, academicYear, classID, majorID, billTypeID, search, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentPayments")
	}

	var r0 []map[string]interface{}
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, uint, uint, uint, string, int, int) ([]map[string]interface{}, int, error)); ok {
		return rf(ctx, start, end, academicYear, classID, majorID, billTypeID, search, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, uint, uint, uint, string, int, int) []map[string]interface{}); ok {
		r0 = rf(ctx, start, end, academicYear, classID, majorID, billTypeID, search, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *time.Time, *time.Time, int, uint, uint, uint, string, int, int) int); ok {
		r1 = rf(ctx, start, end, academicYear, classID, majorID, billTypeID, search, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *time.Time, *time.Time, int, uint, uint, uint, string, int, int) error); ok {
		r2 = rf(ctx, start, end, academicYear, classID, majorID, billTypeID, search, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetTotalBillsByPeriod provides a mock function with given fields: ctx, start, end, academicYear, classID, majorID
func (_m *FinanceReportRepo) GetTotalBillsByPeriod(ctx context.Context, start *time.Time, end *time.Time, academicYear int, classID uint, majorID uint) (float64, error) {
	ret := _m.Called(ctx, start, end, academicYear, classID, majorID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalBillsByPeriod")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, uint, uint) (float64, error)); ok {
		return rf(ctx, start, end, academicYear, classID, majorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, uint, uint) float64); ok {
		r0 = rf(ctx, start, end, academicYear, classID, majorID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *time.Time, *time.Time, int, uint, uint) error); ok {
		r1 = rf(ctx, start, end, academicYear, classID, majorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTotalPaymentsByPeriod provides a mock function with given fields: ctx, start, end, academicYear, classID, majorID
func (_m *FinanceReportRepo) GetTotalPaymentsByPeriod(ctx context.Context, start *time.Time, end *time.Time, academicYear int, classID uint, majorID uint) (float64, error) {
	ret := _m.Called(ctx, start, end, academicYear, classID, majorID)

	if len(ret) == 0 {
		panic("no return value specified for GetTotalPaymentsByPeriod")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, uint, uint) (float64, error)); ok {
		return rf(ctx, start, end, academicYear, classID, majorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, uint, uint) float64); ok {
		r0 = rf(ctx, start, end, academicYear, classID, majorID)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *time.Time, *time.Time, int, uint, uint) error); ok {
		r1 = rf(ctx, start, end, academicYear, classID, majorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewFinanceReportRepo creates a new instance of FinanceReportRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinanceReportRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *FinanceReportRepo {
	mock := &FinanceReportRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
