// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/finance/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// FinanceReportService is an autogenerated mock type for the FinanceReportService type
type FinanceReportService struct {
	mock.Mock
}

// ExportTrendExcel provides a mock function with given fields: ctx, start, end, interval, academicYear, classID, majorID
func (_m *FinanceReportService) ExportTrendExcel(ctx context.Context, start *time.Time, end *time.Time, interval string, academicYear int, classID uint, majorID uint) ([]byte, error) {
	ret := _m.Called(ctx, start, end, interval, academicYear, classID, majorID)

	if len(ret) == 0 {
		panic("no return value specified for ExportTrendExcel")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, string, int, uint, uint) ([]byte, error)); ok {
		return rf(ctx, start, end, interval, academicYear, classID, majorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, string, int, uint, uint) []byte); ok {
		r0 = rf(ctx, start, end, interval, academicYear, classID, majorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *time.Time, *time.Time, string, int, uint, uint) error); ok {
		r1 = rf(ctx, start, end, interval, academicYear, classID, majorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetArrears provides a mock function with given fields: ctx, page, limit, academicYear, classID, majorID, billTypeID, search, start, end
func (_m *FinanceReportService) GetArrears(ctx context.Context, page int, limit int, academicYear int, classID uint, majorID uint, billTypeID uint, search string, start *time.Time, end *time.Time) ([]domain.ArrearRecord, int, error) {
	ret := _m.Called(ctx, page, limit, academicYear, classID, majorID, billTypeID, search, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetArrears")
	}

	var r0 []domain.ArrearRecord
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, uint, uint, uint, string, *time.Time, *time.Time) ([]domain.ArrearRecord, int, error)); ok {
		return rf(ctx, page, limit, academicYear, classID, majorID, billTypeID, search, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, int, uint, uint, uint, string, *time.Time, *time.Time) []domain.ArrearRecord); ok {
		r0 = rf(ctx, page, limit, academicYear, classID, majorID, billTypeID, search, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ArrearRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, int, uint, uint, uint, string, *time.Time, *time.Time) int); ok {
		r1 = rf(ctx, page, limit, academicYear, classID, majorID, billTypeID, search, start, end)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, int, uint, uint, uint, string, *time.Time, *time.Time) error); ok {
		r2 = rf(ctx, page, limit, academicYear, classID, majorID, billTypeID, search, start, end)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewFinanceReportService creates a new instance of FinanceReportService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinanceReportService(t interface {
	mock.TestingT
	Cleanup(func())
}) *FinanceReportService {
	mock := &FinanceReportService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
