// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	usecase "github.com/ahmadzakyarifin/schoolpay/internal/module/notification/usecase"
	mock "github.com/stretchr/testify/mock"
)

// MockFinanceNotificationService is an autogenerated mock type for the FinanceNotificationService type
type MockFinanceNotificationService struct {
	mock.Mock
}

type MockFinanceNotificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFinanceNotificationService) EXPECT() *MockFinanceNotificationService_Expecter {
	return &MockFinanceNotificationService_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function with given fields: job
func (_m *MockFinanceNotificationService) Notify(job usecase.FinanceNotifyJob) {
	_m.Called(job)
}

// MockFinanceNotificationService_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockFinanceNotificationService_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - job usecase.FinanceNotifyJob
func (_e *MockFinanceNotificationService_Expecter) Notify(job interface{}) *MockFinanceNotificationService_Notify_Call {
	return &MockFinanceNotificationService_Notify_Call{Call: _e.mock.On("Notify", job)}
}

func (_c *MockFinanceNotificationService_Notify_Call) Run(run func(job usecase.FinanceNotifyJob)) *MockFinanceNotificationService_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(usecase.FinanceNotifyJob))
	})
	return _c
}

func (_c *MockFinanceNotificationService_Notify_Call) Return() *MockFinanceNotificationService_Notify_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFinanceNotificationService_Notify_Call) RunAndReturn(run func(usecase.FinanceNotifyJob)) *MockFinanceNotificationService_Notify_Call {
	_c.Run(run)
	return _c
}

// NewMockFinanceNotificationService creates a new instance of MockFinanceNotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFinanceNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFinanceNotificationService {
	mock := &MockFinanceNotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
