// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/academic/domain"
	mock "github.com/stretchr/testify/mock"
)

// MajorRepo is an autogenerated mock type for the MajorRepo type
type MajorRepo struct {
	mock.Mock
}

// BulkDelete provides a mock function with given fields: ctx, ids
func (_m *MajorRepo) BulkDelete(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BulkRestore provides a mock function with given fields: ctx, ids
func (_m *MajorRepo) BulkRestore(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkRestore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountAcademicYears provides a mock function with given fields: ctx, majorID
func (_m *MajorRepo) CountAcademicYears(ctx context.Context, majorID uint) (int, error) {
	ret := _m.Called(ctx, majorID)

	if len(ret) == 0 {
		panic("no return value specified for CountAcademicYears")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int, error)); ok {
		return rf(ctx, majorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int); ok {
		r0 = rf(ctx, majorID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, majorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountClasses provides a mock function with given fields: ctx, majorID
func (_m *MajorRepo) CountClasses(ctx context.Context, majorID uint) (int, error) {
	ret := _m.Called(ctx, majorID)

	if len(ret) == 0 {
		panic("no return value specified for CountClasses")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int, error)); ok {
		return rf(ctx, majorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int); ok {
		r0 = rf(ctx, majorID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, majorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountStudents provides a mock function with given fields: ctx, majorID
func (_m *MajorRepo) CountStudents(ctx context.Context, majorID uint) (int, error) {
	ret := _m.Called(ctx, majorID)

	if len(ret) == 0 {
		panic("no return value specified for CountStudents")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (int, error)); ok {
		return rf(ctx, majorID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) int); ok {
		r0 = rf(ctx, majorID)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, majorID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, j
func (_m *MajorRepo) Create(ctx context.Context, j *domain.Major) error {
	ret := _m.Called(ctx, j)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Major) error); ok {
		r0 = rf(ctx, j)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MajorRepo) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: ctx, name, excludeID
func (_m *MajorRepo) Exists(ctx context.Context, name string, excludeID uint) (bool, error) {
	ret := _m.Called(ctx, name, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) (bool, error)); ok {
		return rf(ctx, name, excludeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) bool); ok {
		r0 = rf(ctx, name, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = rf(ctx, name, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExistsByCode provides a mock function with given fields: ctx, code, excludeID
func (_m *MajorRepo) ExistsByCode(ctx context.Context, code string, excludeID uint) (bool, error) {
	ret := _m.Called(ctx, code, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByCode")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) (bool, error)); ok {
		return rf(ctx, code, excludeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) bool); ok {
		r0 = rf(ctx, code, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = rf(ctx, code, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx, page, limit, search, status
func (_m *MajorRepo) FindAll(ctx context.Context, page int, limit int, search string, status string, sort string) ([]domain.Major, int, error) {
	ret := _m.Called(ctx, page, limit, search, status, sort)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Major
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string) ([]domain.Major, int, error)); ok {
		return rf(ctx, page, limit, search, status, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string) []domain.Major); ok {
		r0 = rf(ctx, page, limit, search, status, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Major)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, string) int); ok {
		r1 = rf(ctx, page, limit, search, status, sort)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string, string) error); ok {
		r2 = rf(ctx, page, limit, search, status, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MajorRepo) FindByID(ctx context.Context, id uint) (*domain.Major, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Major
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Major, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Major); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Major)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByName provides a mock function with given fields: ctx, name
func (_m *MajorRepo) FindByName(ctx context.Context, name string) (*domain.Major, error) {
	ret := _m.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *domain.Major
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Major, error)); ok {
		return rf(ctx, name)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Major); ok {
		r0 = rf(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Major)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Restore provides a mock function with given fields: ctx, id
func (_m *MajorRepo) Restore(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ToggleStatus provides a mock function with given fields: ctx, id
func (_m *MajorRepo) ToggleStatus(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ToggleStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, j
func (_m *MajorRepo) Update(ctx context.Context, j *domain.Major) error {
	ret := _m.Called(ctx, j)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Major) error); ok {
		r0 = rf(ctx, j)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMajorRepo creates a new instance of MajorRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMajorRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MajorRepo {
	mock := &MajorRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
