// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bun "github.com/uptrace/bun"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/notification/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// NotificationRepo is an autogenerated mock type for the NotificationRepo type
type NotificationRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, db, n
func (_m *NotificationRepo) Create(ctx context.Context, db bun.IDB, n *domain.Notification) error {
	ret := _m.Called(ctx, db, n)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *domain.Notification) error); ok {
		r0 = rf(ctx, db, n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *NotificationRepo) FindByID(ctx context.Context, id uint) (*domain.Notification, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Notification, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Notification); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *NotificationRepo) GetByUserID(ctx context.Context, userID uint) ([]domain.Notification, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 []domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.Notification, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.Notification); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDetailedLogs provides a mock function with given fields: ctx, page, limit, status, search, channel
func (_m *NotificationRepo) GetDetailedLogs(ctx context.Context, page int, limit int, status string, search string, channel string) ([]map[string]interface{}, int, error) {
	ret := _m.Called(ctx, page, limit, status, search, channel)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailedLogs")
	}

	var r0 []map[string]interface{}
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string) ([]map[string]interface{}, int, error)); ok {
		return rf(ctx, page, limit, status, search, channel)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string) []map[string]interface{}); ok {
		r0 = rf(ctx, page, limit, status, search, channel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, string) int); ok {
		r1 = rf(ctx, page, limit, status, search, channel)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string, string) error); ok {
		r2 = rf(ctx, page, limit, status, search, channel)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetEfficacyStats provides a mock function with given fields: ctx, channel, start, end
func (_m *NotificationRepo) GetEfficacyStats(ctx context.Context, channel string, start *time.Time, end *time.Time) (map[string]int, error) {
	ret := _m.Called(ctx, channel, start, end)

	if len(ret) == 0 {
		panic("no return value specified for GetEfficacyStats")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *time.Time, *time.Time) (map[string]int, error)); ok {
		return rf(ctx, channel, start, end)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, *time.Time, *time.Time) map[string]int); ok {
		r0 = rf(ctx, channel, start, end)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, *time.Time, *time.Time) error); ok {
		r1 = rf(ctx, channel, start, end)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStats provides a mock function with given fields: ctx
func (_m *NotificationRepo) GetStats(ctx context.Context) (map[string]int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkAsRead provides a mock function with given fields: ctx, id
func (_m *NotificationRepo) MarkAsRead(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for MarkAsRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusByWhatsappID provides a mock function with given fields: ctx, whatsappID, status
func (_m *NotificationRepo) UpdateStatusByWhatsappID(ctx context.Context, whatsappID string, status string) error {
	ret := _m.Called(ctx, whatsappID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusByWhatsappID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, whatsappID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationRepo creates a new instance of NotificationRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRepo {
	mock := &NotificationRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
