// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bun "github.com/uptrace/bun"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/finance/domain"
	mock "github.com/stretchr/testify/mock"
)

// PaymentRepo is an autogenerated mock type for the PaymentRepo type
type PaymentRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, db, p
func (_m *PaymentRepo) Create(ctx context.Context, db bun.IDB, p *domain.Payment) error {
	ret := _m.Called(ctx, db, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *domain.Payment) error); ok {
		r0 = rf(ctx, db, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateDetail provides a mock function with given fields: ctx, db, pd
func (_m *PaymentRepo) CreateDetail(ctx context.Context, db bun.IDB, pd *domain.PaymentDetail) error {
	ret := _m.Called(ctx, db, pd)

	if len(ret) == 0 {
		panic("no return value specified for CreateDetail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *domain.PaymentDetail) error); ok {
		r0 = rf(ctx, db, pd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteDetailsByPaymentID provides a mock function with given fields: ctx, db, paymentID
func (_m *PaymentRepo) DeleteDetailsByPaymentID(ctx context.Context, db bun.IDB, paymentID uint) error {
	ret := _m.Called(ctx, db, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDetailsByPaymentID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uint) error); ok {
		r0 = rf(ctx, db, paymentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *PaymentRepo) FindByID(ctx context.Context, id uint) (*domain.Payment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Payment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Payment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByRef provides a mock function with given fields: ctx, ref
func (_m *PaymentRepo) FindByRef(ctx context.Context, ref string) (*domain.Payment, error) {
	ret := _m.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for FindByRef")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Payment, error)); ok {
		return rf(ctx, ref)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Payment); ok {
		r0 = rf(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByStudent provides a mock function with given fields: ctx, studentID
func (_m *PaymentRepo) FindByStudent(ctx context.Context, studentID uint) ([]domain.Payment, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for FindByStudent")
	}

	var r0 []domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.Payment, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.Payment); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindDetailsByPaymentID provides a mock function with given fields: ctx, paymentID
func (_m *PaymentRepo) FindDetailsByPaymentID(ctx context.Context, paymentID uint) ([]domain.PaymentDetail, error) {
	ret := _m.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for FindDetailsByPaymentID")
	}

	var r0 []domain.PaymentDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.PaymentDetail, error)); ok {
		return rf(ctx, paymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.PaymentDetail); ok {
		r0 = rf(ctx, paymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PaymentDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, paymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPaymentRepo creates a new instance of PaymentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentRepo {
	mock := &PaymentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
