// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/finance/domain"
	mock "github.com/stretchr/testify/mock"
)

// PaymentService is an autogenerated mock type for the PaymentService type
type PaymentService struct {
	mock.Mock
}

// CreateIntent provides a mock function with given fields: ctx, studentID, amount, depositApplied, billIDs, isBypassRule
func (_m *PaymentService) CreateIntent(ctx context.Context, studentID uint, amount float64, depositApplied float64, billIDs []uint, isBypassRule bool) (*domain.Payment, error) {
	ret := _m.Called(ctx, studentID, amount, depositApplied, billIDs, isBypassRule)

	if len(ret) == 0 {
		panic("no return value specified for CreateIntent")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, float64, float64, []uint, bool) (*domain.Payment, error)); ok {
		return rf(ctx, studentID, amount, depositApplied, billIDs, isBypassRule)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, float64, float64, []uint, bool) *domain.Payment); ok {
		r0 = rf(ctx, studentID, amount, depositApplied, billIDs, isBypassRule)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, float64, float64, []uint, bool) error); ok {
		r1 = rf(ctx, studentID, amount, depositApplied, billIDs, isBypassRule)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetHistory provides a mock function with given fields: ctx, studentID
func (_m *PaymentService) GetHistory(ctx context.Context, studentID uint) ([]domain.Payment, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetHistory")
	}

	var r0 []domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.Payment, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.Payment); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReceipt provides a mock function with given fields: ctx, paymentID
func (_m *PaymentService) GetReceipt(ctx context.Context, paymentID uint) (*domain.Receipt, error) {
	ret := _m.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for GetReceipt")
	}

	var r0 *domain.Receipt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Receipt, error)); ok {
		return rf(ctx, paymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Receipt); ok {
		r0 = rf(ctx, paymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Receipt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, paymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleWebhook provides a mock function with given fields: ctx, payload
func (_m *PaymentService) HandleWebhook(ctx context.Context, payload map[string]interface{}) error {
	ret := _m.Called(ctx, payload)

	if len(ret) == 0 {
		panic("no return value specified for HandleWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, map[string]interface{}) error); ok {
		r0 = rf(ctx, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Process provides a mock function with given fields: ctx, studentID, p, billIDs
func (_m *PaymentService) Process(ctx context.Context, studentID uint, p *domain.Payment, billIDs []uint) error {
	ret := _m.Called(ctx, studentID, p, billIDs)

	if len(ret) == 0 {
		panic("no return value specified for Process")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, *domain.Payment, []uint) error); ok {
		r0 = rf(ctx, studentID, p, billIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPaymentService creates a new instance of PaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentService {
	mock := &PaymentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
