// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// PaymentGatewayService is an autogenerated mock type for the PaymentGatewayService type
type PaymentGatewayService struct {
	mock.Mock
}

// VerifySignature provides a mock function with given fields: orderID, statusCode, grossAmount, signatureKey
func (_m *PaymentGatewayService) VerifySignature(orderID string, statusCode string, grossAmount string, signatureKey string) bool {
	ret := _m.Called(orderID, statusCode, grossAmount, signatureKey)

	if len(ret) == 0 {
		panic("no return value specified for VerifySignature")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, string, string) bool); ok {
		r0 = rf(orderID, statusCode, grossAmount, signatureKey)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewPaymentGatewayService creates a new instance of PaymentGatewayService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentGatewayService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentGatewayService {
	mock := &PaymentGatewayService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
