// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bun "github.com/uptrace/bun"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/finance/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockPaymentRepo is an autogenerated mock type for the PaymentRepo type
type MockPaymentRepo struct {
	mock.Mock
}

type MockPaymentRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentRepo) EXPECT() *MockPaymentRepo_Expecter {
	return &MockPaymentRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, db, p
func (_m *MockPaymentRepo) Create(ctx context.Context, db bun.IDB, p *domain.Payment) error {
	ret := _m.Called(ctx, db, p)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *domain.Payment) error); ok {
		r0 = rf(ctx, db, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockPaymentRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - db bun.IDB
//   - p *domain.Payment
func (_e *MockPaymentRepo_Expecter) Create(ctx interface{}, db interface{}, p interface{}) *MockPaymentRepo_Create_Call {
	return &MockPaymentRepo_Create_Call{Call: _e.mock.On("Create", ctx, db, p)}
}

func (_c *MockPaymentRepo_Create_Call) Run(run func(ctx context.Context, db bun.IDB, p *domain.Payment)) *MockPaymentRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bun.IDB), args[2].(*domain.Payment))
	})
	return _c
}

func (_c *MockPaymentRepo_Create_Call) Return(_a0 error) *MockPaymentRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepo_Create_Call) RunAndReturn(run func(context.Context, bun.IDB, *domain.Payment) error) *MockPaymentRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDetail provides a mock function with given fields: ctx, db, pd
func (_m *MockPaymentRepo) CreateDetail(ctx context.Context, db bun.IDB, pd *domain.PaymentDetail) error {
	ret := _m.Called(ctx, db, pd)

	if len(ret) == 0 {
		panic("no return value specified for CreateDetail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *domain.PaymentDetail) error); ok {
		r0 = rf(ctx, db, pd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepo_CreateDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDetail'
type MockPaymentRepo_CreateDetail_Call struct {
	*mock.Call
}

// CreateDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - db bun.IDB
//   - pd *domain.PaymentDetail
func (_e *MockPaymentRepo_Expecter) CreateDetail(ctx interface{}, db interface{}, pd interface{}) *MockPaymentRepo_CreateDetail_Call {
	return &MockPaymentRepo_CreateDetail_Call{Call: _e.mock.On("CreateDetail", ctx, db, pd)}
}

func (_c *MockPaymentRepo_CreateDetail_Call) Run(run func(ctx context.Context, db bun.IDB, pd *domain.PaymentDetail)) *MockPaymentRepo_CreateDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bun.IDB), args[2].(*domain.PaymentDetail))
	})
	return _c
}

func (_c *MockPaymentRepo_CreateDetail_Call) Return(_a0 error) *MockPaymentRepo_CreateDetail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepo_CreateDetail_Call) RunAndReturn(run func(context.Context, bun.IDB, *domain.PaymentDetail) error) *MockPaymentRepo_CreateDetail_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDetailsByPaymentID provides a mock function with given fields: ctx, db, paymentID
func (_m *MockPaymentRepo) DeleteDetailsByPaymentID(ctx context.Context, db bun.IDB, paymentID uint) error {
	ret := _m.Called(ctx, db, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDetailsByPaymentID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uint) error); ok {
		r0 = rf(ctx, db, paymentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepo_DeleteDetailsByPaymentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDetailsByPaymentID'
type MockPaymentRepo_DeleteDetailsByPaymentID_Call struct {
	*mock.Call
}

// DeleteDetailsByPaymentID is a helper method to define mock.On call
//   - ctx context.Context
//   - db bun.IDB
//   - paymentID uint
func (_e *MockPaymentRepo_Expecter) DeleteDetailsByPaymentID(ctx interface{}, db interface{}, paymentID interface{}) *MockPaymentRepo_DeleteDetailsByPaymentID_Call {
	return &MockPaymentRepo_DeleteDetailsByPaymentID_Call{Call: _e.mock.On("DeleteDetailsByPaymentID", ctx, db, paymentID)}
}

func (_c *MockPaymentRepo_DeleteDetailsByPaymentID_Call) Run(run func(ctx context.Context, db bun.IDB, paymentID uint)) *MockPaymentRepo_DeleteDetailsByPaymentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bun.IDB), args[2].(uint))
	})
	return _c
}

func (_c *MockPaymentRepo_DeleteDetailsByPaymentID_Call) Return(_a0 error) *MockPaymentRepo_DeleteDetailsByPaymentID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepo_DeleteDetailsByPaymentID_Call) RunAndReturn(run func(context.Context, bun.IDB, uint) error) *MockPaymentRepo_DeleteDetailsByPaymentID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockPaymentRepo) FindByID(ctx context.Context, id uint) (*domain.Payment, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Payment, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Payment); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockPaymentRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockPaymentRepo_Expecter) FindByID(ctx interface{}, id interface{}) *MockPaymentRepo_FindByID_Call {
	return &MockPaymentRepo_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockPaymentRepo_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockPaymentRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockPaymentRepo_FindByID_Call) Return(_a0 *domain.Payment, _a1 error) *MockPaymentRepo_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepo_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*domain.Payment, error)) *MockPaymentRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByRef provides a mock function with given fields: ctx, ref
func (_m *MockPaymentRepo) FindByRef(ctx context.Context, ref string) (*domain.Payment, error) {
	ret := _m.Called(ctx, ref)

	if len(ret) == 0 {
		panic("no return value specified for FindByRef")
	}

	var r0 *domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Payment, error)); ok {
		return rf(ctx, ref)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Payment); ok {
		r0 = rf(ctx, ref)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, ref)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepo_FindByRef_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByRef'
type MockPaymentRepo_FindByRef_Call struct {
	*mock.Call
}

// FindByRef is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
func (_e *MockPaymentRepo_Expecter) FindByRef(ctx interface{}, ref interface{}) *MockPaymentRepo_FindByRef_Call {
	return &MockPaymentRepo_FindByRef_Call{Call: _e.mock.On("FindByRef", ctx, ref)}
}

func (_c *MockPaymentRepo_FindByRef_Call) Run(run func(ctx context.Context, ref string)) *MockPaymentRepo_FindByRef_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentRepo_FindByRef_Call) Return(_a0 *domain.Payment, _a1 error) *MockPaymentRepo_FindByRef_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepo_FindByRef_Call) RunAndReturn(run func(context.Context, string) (*domain.Payment, error)) *MockPaymentRepo_FindByRef_Call {
	_c.Call.Return(run)
	return _c
}

// FindByStudent provides a mock function with given fields: ctx, studentID
func (_m *MockPaymentRepo) FindByStudent(ctx context.Context, studentID uint) ([]domain.Payment, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for FindByStudent")
	}

	var r0 []domain.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.Payment, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.Payment); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepo_FindByStudent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByStudent'
type MockPaymentRepo_FindByStudent_Call struct {
	*mock.Call
}

// FindByStudent is a helper method to define mock.On call
//   - ctx context.Context
//   - studentID uint
func (_e *MockPaymentRepo_Expecter) FindByStudent(ctx interface{}, studentID interface{}) *MockPaymentRepo_FindByStudent_Call {
	return &MockPaymentRepo_FindByStudent_Call{Call: _e.mock.On("FindByStudent", ctx, studentID)}
}

func (_c *MockPaymentRepo_FindByStudent_Call) Run(run func(ctx context.Context, studentID uint)) *MockPaymentRepo_FindByStudent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockPaymentRepo_FindByStudent_Call) Return(_a0 []domain.Payment, _a1 error) *MockPaymentRepo_FindByStudent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepo_FindByStudent_Call) RunAndReturn(run func(context.Context, uint) ([]domain.Payment, error)) *MockPaymentRepo_FindByStudent_Call {
	_c.Call.Return(run)
	return _c
}

// FindDetailsByPaymentID provides a mock function with given fields: ctx, paymentID
func (_m *MockPaymentRepo) FindDetailsByPaymentID(ctx context.Context, paymentID uint) ([]domain.PaymentDetail, error) {
	ret := _m.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for FindDetailsByPaymentID")
	}

	var r0 []domain.PaymentDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.PaymentDetail, error)); ok {
		return rf(ctx, paymentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.PaymentDetail); ok {
		r0 = rf(ctx, paymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PaymentDetail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, paymentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentRepo_FindDetailsByPaymentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDetailsByPaymentID'
type MockPaymentRepo_FindDetailsByPaymentID_Call struct {
	*mock.Call
}

// FindDetailsByPaymentID is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID uint
func (_e *MockPaymentRepo_Expecter) FindDetailsByPaymentID(ctx interface{}, paymentID interface{}) *MockPaymentRepo_FindDetailsByPaymentID_Call {
	return &MockPaymentRepo_FindDetailsByPaymentID_Call{Call: _e.mock.On("FindDetailsByPaymentID", ctx, paymentID)}
}

func (_c *MockPaymentRepo_FindDetailsByPaymentID_Call) Run(run func(ctx context.Context, paymentID uint)) *MockPaymentRepo_FindDetailsByPaymentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockPaymentRepo_FindDetailsByPaymentID_Call) Return(_a0 []domain.PaymentDetail, _a1 error) *MockPaymentRepo_FindDetailsByPaymentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentRepo_FindDetailsByPaymentID_Call) RunAndReturn(run func(context.Context, uint) ([]domain.PaymentDetail, error)) *MockPaymentRepo_FindDetailsByPaymentID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentRepo creates a new instance of MockPaymentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepo {
	mock := &MockPaymentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
