// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/academic/domain"
	mock "github.com/stretchr/testify/mock"

	user_authdomain "github.com/ahmadzakyarifin/schoolpay/internal/module/user_auth/domain"
)

// StudentService is an autogenerated mock type for the StudentService type
type StudentService struct {
	mock.Mock
}

// BulkDelete provides a mock function with given fields: ctx, ids
func (_m *StudentService) BulkDelete(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BulkGraduate provides a mock function with given fields: ctx, classID, studentIDs
func (_m *StudentService) BulkGraduate(ctx context.Context, classID uint, studentIDs []uint) error {
	ret := _m.Called(ctx, classID, studentIDs)

	if len(ret) == 0 {
		panic("no return value specified for BulkGraduate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, []uint) error); ok {
		r0 = rf(ctx, classID, studentIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BulkPromote provides a mock function with given fields: ctx, sourceClassID, targetClassID, studentIDs
func (_m *StudentService) BulkPromote(ctx context.Context, sourceClassID uint, targetClassID uint, studentIDs []uint) error {
	ret := _m.Called(ctx, sourceClassID, targetClassID, studentIDs)

	if len(ret) == 0 {
		panic("no return value specified for BulkPromote")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, []uint) error); ok {
		r0 = rf(ctx, sourceClassID, targetClassID, studentIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BulkRestore provides a mock function with given fields: ctx, ids
func (_m *StudentService) BulkRestore(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkRestore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, s
func (_m *StudentService) Create(ctx context.Context, s *domain.Student) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Student) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *StudentService) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExportExcel provides a mock function with given fields: ctx, search, filter, status, entryYear, classID, majorID, sort
func (_m *StudentService) ExportExcel(ctx context.Context, search string, filter string, status string, entryYear int, classID uint, majorID uint, sort string) ([]byte, error) {
	ret := _m.Called(ctx, search, filter, status, entryYear, classID, majorID, sort)

	if len(ret) == 0 {
		panic("no return value specified for ExportExcel")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, uint, uint, string) ([]byte, error)); ok {
		return rf(ctx, search, filter, status, entryYear, classID, majorID, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, uint, uint, string) []byte); ok {
		r0 = rf(ctx, search, filter, status, entryYear, classID, majorID, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int, uint, uint, string) error); ok {
		r1 = rf(ctx, search, filter, status, entryYear, classID, majorID, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAcademicFilters provides a mock function with given fields: ctx
func (_m *StudentService) GetAcademicFilters(ctx context.Context) (map[string]interface{}, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAcademicFilters")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]interface{}, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]interface{}); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *StudentService) GetByID(ctx context.Context, id uint) (*domain.Student, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Student, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Student); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClassHistory provides a mock function with given fields: ctx, studentID
func (_m *StudentService) GetClassHistory(ctx context.Context, studentID uint) ([]domain.ClassHistory, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetClassHistory")
	}

	var r0 []domain.ClassHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.ClassHistory, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.ClassHistory); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ClassHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDependencyInfo provides a mock function with given fields: ctx, id
func (_m *StudentService) GetDependencyInfo(ctx context.Context, id uint) (map[string]interface{}, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDependencyInfo")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (map[string]interface{}, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) map[string]interface{}); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaginated provides a mock function with given fields: ctx, page, limit, search, filter, status, entryYear, classID, majorID, sort
func (_m *StudentService) GetPaginated(ctx context.Context, page int, limit int, search string, filter string, status string, entryYear int, classID uint, majorID uint, sort string) ([]domain.Student, int, error) {
	ret := _m.Called(ctx, page, limit, search, filter, status, entryYear, classID, majorID, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetPaginated")
	}

	var r0 []domain.Student
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, int, uint, uint, string) ([]domain.Student, int, error)); ok {
		return rf(ctx, page, limit, search, filter, status, entryYear, classID, majorID, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, int, uint, uint, string) []domain.Student); ok {
		r0 = rf(ctx, page, limit, search, filter, status, entryYear, classID, majorID, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, string, int, uint, uint, string) int); ok {
		r1 = rf(ctx, page, limit, search, filter, status, entryYear, classID, majorID, sort)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string, string, int, uint, uint, string) error); ok {
		r2 = rf(ctx, page, limit, search, filter, status, entryYear, classID, majorID, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetParents provides a mock function with given fields: ctx, studentID
func (_m *StudentService) GetParents(ctx context.Context, studentID uint) ([]user_authdomain.User, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetParents")
	}

	var r0 []user_authdomain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]user_authdomain.User, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []user_authdomain.User); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user_authdomain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudentsByParentID provides a mock function with given fields: ctx, parentID
func (_m *StudentService) GetStudentsByParentID(ctx context.Context, parentID uint) ([]domain.Student, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentsByParentID")
	}

	var r0 []domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.Student, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.Student); ok {
		r0 = rf(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Restore provides a mock function with given fields: ctx, id
func (_m *StudentService) Restore(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ToggleStatus provides a mock function with given fields: ctx, id
func (_m *StudentService) ToggleStatus(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ToggleStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, s
func (_m *StudentService) Update(ctx context.Context, s *domain.Student) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Student) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStudentService creates a new instance of StudentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStudentService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StudentService {
	mock := &StudentService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
