// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bun "github.com/uptrace/bun"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/finance/domain"
	mock "github.com/stretchr/testify/mock"
)

// StudentBillRepo is an autogenerated mock type for the StudentBillRepo type
type StudentBillRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, db, sb
func (_m *StudentBillRepo) Create(ctx context.Context, db bun.IDB, sb *domain.StudentBill) error {
	ret := _m.Called(ctx, db, sb)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *domain.StudentBill) error); ok {
		r0 = rf(ctx, db, sb)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *StudentBillRepo) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExistsByPeriod provides a mock function with given fields: ctx, studentID, billTypeID, period
func (_m *StudentBillRepo) ExistsByPeriod(ctx context.Context, studentID uint, billTypeID uint, period string) (bool, error) {
	ret := _m.Called(ctx, studentID, billTypeID, period)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByPeriod")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) (bool, error)); ok {
		return rf(ctx, studentID, billTypeID, period)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) bool); ok {
		r0 = rf(ctx, studentID, billTypeID, period)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, string) error); ok {
		r1 = rf(ctx, studentID, billTypeID, period)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExistsByPeriodExcludeID provides a mock function with given fields: ctx, studentID, billTypeID, period, excludeID
func (_m *StudentBillRepo) ExistsByPeriodExcludeID(ctx context.Context, studentID uint, billTypeID uint, period string, excludeID uint) (bool, error) {
	ret := _m.Called(ctx, studentID, billTypeID, period, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByPeriodExcludeID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string, uint) (bool, error)); ok {
		return rf(ctx, studentID, billTypeID, period, excludeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string, uint) bool); ok {
		r0 = rf(ctx, studentID, billTypeID, period, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, string, uint) error); ok {
		r1 = rf(ctx, studentID, billTypeID, period, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAll provides a mock function with given fields: ctx, search, sort
func (_m *StudentBillRepo) FindAll(ctx context.Context, search string, sort string) ([]domain.StudentBill, error) {
	ret := _m.Called(ctx, search, sort)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.StudentBill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.StudentBill, error)); ok {
		return rf(ctx, search, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []domain.StudentBill); ok {
		r0 = rf(ctx, search, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudentBill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, search, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *StudentBillRepo) FindByID(ctx context.Context, id uint) (*domain.StudentBill, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.StudentBill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.StudentBill, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.StudentBill); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StudentBill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByParent provides a mock function with given fields: ctx, parentID
func (_m *StudentBillRepo) FindByParent(ctx context.Context, parentID uint) ([]domain.StudentBill, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for FindByParent")
	}

	var r0 []domain.StudentBill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.StudentBill, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.StudentBill); ok {
		r0 = rf(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudentBill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByStudent provides a mock function with given fields: ctx, studentID
func (_m *StudentBillRepo) FindByStudent(ctx context.Context, studentID uint) ([]domain.StudentBill, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for FindByStudent")
	}

	var r0 []domain.StudentBill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.StudentBill, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.StudentBill); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudentBill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindForReminder provides a mock function with given fields: ctx, dueInDays, overdueOnly
func (_m *StudentBillRepo) FindForReminder(ctx context.Context, dueInDays int, overdueOnly bool) ([]domain.StudentBill, error) {
	ret := _m.Called(ctx, dueInDays, overdueOnly)

	if len(ret) == 0 {
		panic("no return value specified for FindForReminder")
	}

	var r0 []domain.StudentBill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, bool) ([]domain.StudentBill, error)); ok {
		return rf(ctx, dueInDays, overdueOnly)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, bool) []domain.StudentBill); ok {
		r0 = rf(ctx, dueInDays, overdueOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudentBill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, bool) error); ok {
		r1 = rf(ctx, dueInDays, overdueOnly)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUnpaidBillsByStudent provides a mock function with given fields: ctx, studentID
func (_m *StudentBillRepo) FindUnpaidBillsByStudent(ctx context.Context, studentID uint) ([]domain.StudentBill, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for FindUnpaidBillsByStudent")
	}

	var r0 []domain.StudentBill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.StudentBill, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.StudentBill); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudentBill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, db, sb
func (_m *StudentBillRepo) Update(ctx context.Context, db bun.IDB, sb *domain.StudentBill) error {
	ret := _m.Called(ctx, db, sb)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *domain.StudentBill) error); ok {
		r0 = rf(ctx, db, sb)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: ctx, db, id, status, totalPaid
func (_m *StudentBillRepo) UpdateStatus(ctx context.Context, db bun.IDB, id uint, status string, totalPaid float64) error {
	ret := _m.Called(ctx, db, id, status, totalPaid)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uint, string, float64) error); ok {
		r0 = rf(ctx, db, id, status, totalPaid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStudentBillRepo creates a new instance of StudentBillRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStudentBillRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *StudentBillRepo {
	mock := &StudentBillRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
