// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/finance/domain"
	mock "github.com/stretchr/testify/mock"
)

type StudentBillService struct {
	mock.Mock
}

// BulkGenerateFromRules provides a mock function with given fields: ctx, ruleIDs, customReason, customMessage, skipNotification
func (_m *StudentBillService) BulkGenerateFromRules(ctx context.Context, ruleIDs []uint, customReason string, customMessage string, skipNotification bool) error {
	ret := _m.Called(ctx, ruleIDs, customReason, customMessage, skipNotification)

	if len(ret) == 0 {
		panic("no return value specified for BulkGenerateFromRules")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint, string, string, bool) error); ok {
		r0 = rf(ctx, ruleIDs, customReason, customMessage, skipNotification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CancelGeneratedBills provides a mock function with given fields: ctx, ruleIDs, customReason, customMessage, skipNotification
func (_m *StudentBillService) CancelGeneratedBills(ctx context.Context, ruleIDs []uint, customReason string, customMessage string, skipNotification bool) error {
	ret := _m.Called(ctx, ruleIDs, customReason, customMessage, skipNotification)

	if len(ret) == 0 {
		panic("no return value specified for CancelGeneratedBills")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint, string, string, bool) error); ok {
		r0 = rf(ctx, ruleIDs, customReason, customMessage, skipNotification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, sb
func (_m *StudentBillService) Create(ctx context.Context, sb *domain.StudentBill) error {
	ret := _m.Called(ctx, sb)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StudentBill) error); ok {
		r0 = rf(ctx, sb)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id, reason
func (_m *StudentBillService) Delete(ctx context.Context, id uint, reason ...string) error {
	var _ca []interface{}
	_ca = append(_ca, ctx, id)
	for _, item := range reason {
		_ca = append(_ca, item)
	}
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, ...string) error); ok {
		r0 = rf(ctx, id, reason...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GenerateFromRule provides a mock function with given fields: ctx, ruleID, customReason, customMessage, skipNotification
func (_m *StudentBillService) GenerateFromRule(ctx context.Context, ruleID uint, customReason string, customMessage string, skipNotification bool) error {
	ret := _m.Called(ctx, ruleID, customReason, customMessage, skipNotification)

	if len(ret) == 0 {
		panic("no return value specified for GenerateFromRule")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, string, bool) error); ok {
		r0 = rf(ctx, ruleID, customReason, customMessage, skipNotification)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, search, sort
func (_m *StudentBillService) GetAll(ctx context.Context, search string, sort string) ([]domain.StudentBill, error) {
	ret := _m.Called(ctx, search, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.StudentBill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.StudentBill, error)); ok {
		return rf(ctx, search, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []domain.StudentBill); ok {
		r0 = rf(ctx, search, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudentBill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, search, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudentSummaries provides a mock function with given fields: ctx, search, sort, status, page, limit
func (_m *StudentBillService) GetStudentSummaries(ctx context.Context, search string, sort string, status string, page int, limit int) ([]domain.StudentBillSummary, int, error) {
	ret := _m.Called(ctx, search, sort, status, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentSummaries")
	}

	var r0 []domain.StudentBillSummary
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) ([]domain.StudentBillSummary, int, error)); ok {
		return rf(ctx, search, sort, status, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) []domain.StudentBillSummary); ok {
		r0 = rf(ctx, search, sort, status, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudentBillSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int, int) int); ok {
		r1 = rf(ctx, search, sort, status, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, int, int) error); ok {
		r2 = rf(ctx, search, sort, status, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *StudentBillService) GetByID(ctx context.Context, id uint) (*domain.StudentBill, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.StudentBill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.StudentBill, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.StudentBill); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StudentBill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByParent provides a mock function with given fields: ctx, parentID
func (_m *StudentBillService) GetByParent(ctx context.Context, parentID uint) ([]domain.StudentBill, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByParent")
	}

	var r0 []domain.StudentBill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.StudentBill, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.StudentBill); ok {
		r0 = rf(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudentBill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByStudent provides a mock function with given fields: ctx, studentID
func (_m *StudentBillService) GetByStudent(ctx context.Context, studentID uint) ([]domain.StudentBill, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetByStudent")
	}

	var r0 []domain.StudentBill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.StudentBill, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.StudentBill); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudentBill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RunScheduler provides a mock function with no fields
func (_m *StudentBillService) RunScheduler() {
	_m.Called()
}

// SendManualReminder provides a mock function with given fields: ctx, id
func (_m *StudentBillService) SendManualReminder(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for SendManualReminder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, sb
func (_m *StudentBillService) Update(ctx context.Context, sb *domain.StudentBill) error {
	ret := _m.Called(ctx, sb)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.StudentBill) error); ok {
		r0 = rf(ctx, sb)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStudentBillService creates a new instance of StudentBillService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStudentBillService(t interface {
	mock.TestingT
	Cleanup(func())
}) *StudentBillService {
	mock := &StudentBillService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
