// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bun "github.com/uptrace/bun"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/finance/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockStudentBillRepo is an autogenerated mock type for the StudentBillRepo type
type MockStudentBillRepo struct {
	mock.Mock
}

type MockStudentBillRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStudentBillRepo) EXPECT() *MockStudentBillRepo_Expecter {
	return &MockStudentBillRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, db, sb
func (_m *MockStudentBillRepo) Create(ctx context.Context, db bun.IDB, sb *domain.StudentBill) error {
	ret := _m.Called(ctx, db, sb)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *domain.StudentBill) error); ok {
		r0 = rf(ctx, db, sb)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStudentBillRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockStudentBillRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - db bun.IDB
//   - sb *domain.StudentBill
func (_e *MockStudentBillRepo_Expecter) Create(ctx interface{}, db interface{}, sb interface{}) *MockStudentBillRepo_Create_Call {
	return &MockStudentBillRepo_Create_Call{Call: _e.mock.On("Create", ctx, db, sb)}
}

func (_c *MockStudentBillRepo_Create_Call) Run(run func(ctx context.Context, db bun.IDB, sb *domain.StudentBill)) *MockStudentBillRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bun.IDB), args[2].(*domain.StudentBill))
	})
	return _c
}

func (_c *MockStudentBillRepo_Create_Call) Return(_a0 error) *MockStudentBillRepo_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStudentBillRepo_Create_Call) RunAndReturn(run func(context.Context, bun.IDB, *domain.StudentBill) error) *MockStudentBillRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockStudentBillRepo) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStudentBillRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockStudentBillRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockStudentBillRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockStudentBillRepo_Delete_Call {
	return &MockStudentBillRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockStudentBillRepo_Delete_Call) Run(run func(ctx context.Context, id uint)) *MockStudentBillRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockStudentBillRepo_Delete_Call) Return(_a0 error) *MockStudentBillRepo_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStudentBillRepo_Delete_Call) RunAndReturn(run func(context.Context, uint) error) *MockStudentBillRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByPeriod provides a mock function with given fields: ctx, studentID, billTypeID, period
func (_m *MockStudentBillRepo) ExistsByPeriod(ctx context.Context, studentID uint, billTypeID uint, period string) (bool, error) {
	ret := _m.Called(ctx, studentID, billTypeID, period)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByPeriod")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) (bool, error)); ok {
		return rf(ctx, studentID, billTypeID, period)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) bool); ok {
		r0 = rf(ctx, studentID, billTypeID, period)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, string) error); ok {
		r1 = rf(ctx, studentID, billTypeID, period)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudentBillRepo_ExistsByPeriod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByPeriod'
type MockStudentBillRepo_ExistsByPeriod_Call struct {
	*mock.Call
}

// ExistsByPeriod is a helper method to define mock.On call
//   - ctx context.Context
//   - studentID uint
//   - billTypeID uint
//   - period string
func (_e *MockStudentBillRepo_Expecter) ExistsByPeriod(ctx interface{}, studentID interface{}, billTypeID interface{}, period interface{}) *MockStudentBillRepo_ExistsByPeriod_Call {
	return &MockStudentBillRepo_ExistsByPeriod_Call{Call: _e.mock.On("ExistsByPeriod", ctx, studentID, billTypeID, period)}
}

func (_c *MockStudentBillRepo_ExistsByPeriod_Call) Run(run func(ctx context.Context, studentID uint, billTypeID uint, period string)) *MockStudentBillRepo_ExistsByPeriod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(string))
	})
	return _c
}

func (_c *MockStudentBillRepo_ExistsByPeriod_Call) Return(_a0 bool, _a1 error) *MockStudentBillRepo_ExistsByPeriod_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudentBillRepo_ExistsByPeriod_Call) RunAndReturn(run func(context.Context, uint, uint, string) (bool, error)) *MockStudentBillRepo_ExistsByPeriod_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsByPeriodExcludeID provides a mock function with given fields: ctx, studentID, billTypeID, period, excludeID
func (_m *MockStudentBillRepo) ExistsByPeriodExcludeID(ctx context.Context, studentID uint, billTypeID uint, period string, excludeID uint) (bool, error) {
	ret := _m.Called(ctx, studentID, billTypeID, period, excludeID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByPeriodExcludeID")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string, uint) (bool, error)); ok {
		return rf(ctx, studentID, billTypeID, period, excludeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string, uint) bool); ok {
		r0 = rf(ctx, studentID, billTypeID, period, excludeID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, uint, string, uint) error); ok {
		r1 = rf(ctx, studentID, billTypeID, period, excludeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudentBillRepo_ExistsByPeriodExcludeID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByPeriodExcludeID'
type MockStudentBillRepo_ExistsByPeriodExcludeID_Call struct {
	*mock.Call
}

// ExistsByPeriodExcludeID is a helper method to define mock.On call
//   - ctx context.Context
//   - studentID uint
//   - billTypeID uint
//   - period string
//   - excludeID uint
func (_e *MockStudentBillRepo_Expecter) ExistsByPeriodExcludeID(ctx interface{}, studentID interface{}, billTypeID interface{}, period interface{}, excludeID interface{}) *MockStudentBillRepo_ExistsByPeriodExcludeID_Call {
	return &MockStudentBillRepo_ExistsByPeriodExcludeID_Call{Call: _e.mock.On("ExistsByPeriodExcludeID", ctx, studentID, billTypeID, period, excludeID)}
}

func (_c *MockStudentBillRepo_ExistsByPeriodExcludeID_Call) Run(run func(ctx context.Context, studentID uint, billTypeID uint, period string, excludeID uint)) *MockStudentBillRepo_ExistsByPeriodExcludeID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint), args[2].(uint), args[3].(string), args[4].(uint))
	})
	return _c
}

func (_c *MockStudentBillRepo_ExistsByPeriodExcludeID_Call) Return(_a0 bool, _a1 error) *MockStudentBillRepo_ExistsByPeriodExcludeID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudentBillRepo_ExistsByPeriodExcludeID_Call) RunAndReturn(run func(context.Context, uint, uint, string, uint) (bool, error)) *MockStudentBillRepo_ExistsByPeriodExcludeID_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, search, sort
func (_m *MockStudentBillRepo) FindAll(ctx context.Context, search string, sort string) ([]domain.StudentBill, error) {
	ret := _m.Called(ctx, search, sort)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.StudentBill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]domain.StudentBill, error)); ok {
		return rf(ctx, search, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []domain.StudentBill); ok {
		r0 = rf(ctx, search, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudentBill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, search, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudentBillRepo_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockStudentBillRepo_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - search string
//   - sort string
func (_e *MockStudentBillRepo_Expecter) FindAll(ctx interface{}, search interface{}, sort interface{}) *MockStudentBillRepo_FindAll_Call {
	return &MockStudentBillRepo_FindAll_Call{Call: _e.mock.On("FindAll", ctx, search, sort)}
}

func (_c *MockStudentBillRepo_FindAll_Call) Run(run func(ctx context.Context, search string, sort string)) *MockStudentBillRepo_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockStudentBillRepo_FindAll_Call) Return(_a0 []domain.StudentBill, _a1 error) *MockStudentBillRepo_FindAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudentBillRepo_FindAll_Call) RunAndReturn(run func(context.Context, string, string) ([]domain.StudentBill, error)) *MockStudentBillRepo_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindStudentSummaries provides a mock function with given fields: ctx, search, sort, status, page, limit
func (_m *MockStudentBillRepo) FindStudentSummaries(ctx context.Context, search string, sort string, status string, page int, limit int) ([]domain.StudentBillSummary, int, error) {
	ret := _m.Called(ctx, search, sort, status, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindStudentSummaries")
	}

	var r0 []domain.StudentBillSummary
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) ([]domain.StudentBillSummary, int, error)); ok {
		return rf(ctx, search, sort, status, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, int, int) []domain.StudentBillSummary); ok {
		r0 = rf(ctx, search, sort, status, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudentBillSummary)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, int, int) int); ok {
		r1 = rf(ctx, search, sort, status, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}
	if rf, ok := ret.Get(2).(func(context.Context, string, string, string, int, int) error); ok {
		r2 = rf(ctx, search, sort, status, page, limit)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockStudentBillRepo) FindByID(ctx context.Context, id uint) (*domain.StudentBill, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.StudentBill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.StudentBill, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.StudentBill); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.StudentBill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudentBillRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockStudentBillRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockStudentBillRepo_Expecter) FindByID(ctx interface{}, id interface{}) *MockStudentBillRepo_FindByID_Call {
	return &MockStudentBillRepo_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockStudentBillRepo_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockStudentBillRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockStudentBillRepo_FindByID_Call) Return(_a0 *domain.StudentBill, _a1 error) *MockStudentBillRepo_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudentBillRepo_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*domain.StudentBill, error)) *MockStudentBillRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByParent provides a mock function with given fields: ctx, parentID
func (_m *MockStudentBillRepo) FindByParent(ctx context.Context, parentID uint) ([]domain.StudentBill, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for FindByParent")
	}

	var r0 []domain.StudentBill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.StudentBill, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.StudentBill); ok {
		r0 = rf(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudentBill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudentBillRepo_FindByParent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByParent'
type MockStudentBillRepo_FindByParent_Call struct {
	*mock.Call
}

// FindByParent is a helper method to define mock.On call
//   - ctx context.Context
//   - parentID uint
func (_e *MockStudentBillRepo_Expecter) FindByParent(ctx interface{}, parentID interface{}) *MockStudentBillRepo_FindByParent_Call {
	return &MockStudentBillRepo_FindByParent_Call{Call: _e.mock.On("FindByParent", ctx, parentID)}
}

func (_c *MockStudentBillRepo_FindByParent_Call) Run(run func(ctx context.Context, parentID uint)) *MockStudentBillRepo_FindByParent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockStudentBillRepo_FindByParent_Call) Return(_a0 []domain.StudentBill, _a1 error) *MockStudentBillRepo_FindByParent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudentBillRepo_FindByParent_Call) RunAndReturn(run func(context.Context, uint) ([]domain.StudentBill, error)) *MockStudentBillRepo_FindByParent_Call {
	_c.Call.Return(run)
	return _c
}

// FindByStudent provides a mock function with given fields: ctx, studentID
func (_m *MockStudentBillRepo) FindByStudent(ctx context.Context, studentID uint) ([]domain.StudentBill, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for FindByStudent")
	}

	var r0 []domain.StudentBill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.StudentBill, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.StudentBill); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudentBill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudentBillRepo_FindByStudent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByStudent'
type MockStudentBillRepo_FindByStudent_Call struct {
	*mock.Call
}

// FindByStudent is a helper method to define mock.On call
//   - ctx context.Context
//   - studentID uint
func (_e *MockStudentBillRepo_Expecter) FindByStudent(ctx interface{}, studentID interface{}) *MockStudentBillRepo_FindByStudent_Call {
	return &MockStudentBillRepo_FindByStudent_Call{Call: _e.mock.On("FindByStudent", ctx, studentID)}
}

func (_c *MockStudentBillRepo_FindByStudent_Call) Run(run func(ctx context.Context, studentID uint)) *MockStudentBillRepo_FindByStudent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockStudentBillRepo_FindByStudent_Call) Return(_a0 []domain.StudentBill, _a1 error) *MockStudentBillRepo_FindByStudent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudentBillRepo_FindByStudent_Call) RunAndReturn(run func(context.Context, uint) ([]domain.StudentBill, error)) *MockStudentBillRepo_FindByStudent_Call {
	_c.Call.Return(run)
	return _c
}

// FindForReminder provides a mock function with given fields: ctx, dueInDays, overdueOnly
func (_m *MockStudentBillRepo) FindForReminder(ctx context.Context, dueInDays int, overdueOnly bool) ([]domain.StudentBill, error) {
	ret := _m.Called(ctx, dueInDays, overdueOnly)

	if len(ret) == 0 {
		panic("no return value specified for FindForReminder")
	}

	var r0 []domain.StudentBill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, bool) ([]domain.StudentBill, error)); ok {
		return rf(ctx, dueInDays, overdueOnly)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, bool) []domain.StudentBill); ok {
		r0 = rf(ctx, dueInDays, overdueOnly)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudentBill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, bool) error); ok {
		r1 = rf(ctx, dueInDays, overdueOnly)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudentBillRepo_FindForReminder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindForReminder'
type MockStudentBillRepo_FindForReminder_Call struct {
	*mock.Call
}

// FindForReminder is a helper method to define mock.On call
//   - ctx context.Context
//   - dueInDays int
//   - overdueOnly bool
func (_e *MockStudentBillRepo_Expecter) FindForReminder(ctx interface{}, dueInDays interface{}, overdueOnly interface{}) *MockStudentBillRepo_FindForReminder_Call {
	return &MockStudentBillRepo_FindForReminder_Call{Call: _e.mock.On("FindForReminder", ctx, dueInDays, overdueOnly)}
}

func (_c *MockStudentBillRepo_FindForReminder_Call) Run(run func(ctx context.Context, dueInDays int, overdueOnly bool)) *MockStudentBillRepo_FindForReminder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(bool))
	})
	return _c
}

func (_c *MockStudentBillRepo_FindForReminder_Call) Return(_a0 []domain.StudentBill, _a1 error) *MockStudentBillRepo_FindForReminder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudentBillRepo_FindForReminder_Call) RunAndReturn(run func(context.Context, int, bool) ([]domain.StudentBill, error)) *MockStudentBillRepo_FindForReminder_Call {
	_c.Call.Return(run)
	return _c
}

// FindUnpaidBillsByStudent provides a mock function with given fields: ctx, studentID
func (_m *MockStudentBillRepo) FindUnpaidBillsByStudent(ctx context.Context, studentID uint) ([]domain.StudentBill, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for FindUnpaidBillsByStudent")
	}

	var r0 []domain.StudentBill
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.StudentBill, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.StudentBill); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.StudentBill)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStudentBillRepo_FindUnpaidBillsByStudent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUnpaidBillsByStudent'
type MockStudentBillRepo_FindUnpaidBillsByStudent_Call struct {
	*mock.Call
}

// FindUnpaidBillsByStudent is a helper method to define mock.On call
//   - ctx context.Context
//   - studentID uint
func (_e *MockStudentBillRepo_Expecter) FindUnpaidBillsByStudent(ctx interface{}, studentID interface{}) *MockStudentBillRepo_FindUnpaidBillsByStudent_Call {
	return &MockStudentBillRepo_FindUnpaidBillsByStudent_Call{Call: _e.mock.On("FindUnpaidBillsByStudent", ctx, studentID)}
}

func (_c *MockStudentBillRepo_FindUnpaidBillsByStudent_Call) Run(run func(ctx context.Context, studentID uint)) *MockStudentBillRepo_FindUnpaidBillsByStudent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockStudentBillRepo_FindUnpaidBillsByStudent_Call) Return(_a0 []domain.StudentBill, _a1 error) *MockStudentBillRepo_FindUnpaidBillsByStudent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStudentBillRepo_FindUnpaidBillsByStudent_Call) RunAndReturn(run func(context.Context, uint) ([]domain.StudentBill, error)) *MockStudentBillRepo_FindUnpaidBillsByStudent_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, db, sb
func (_m *MockStudentBillRepo) Update(ctx context.Context, db bun.IDB, sb *domain.StudentBill) error {
	ret := _m.Called(ctx, db, sb)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *domain.StudentBill) error); ok {
		r0 = rf(ctx, db, sb)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStudentBillRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockStudentBillRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - db bun.IDB
//   - sb *domain.StudentBill
func (_e *MockStudentBillRepo_Expecter) Update(ctx interface{}, db interface{}, sb interface{}) *MockStudentBillRepo_Update_Call {
	return &MockStudentBillRepo_Update_Call{Call: _e.mock.On("Update", ctx, db, sb)}
}

func (_c *MockStudentBillRepo_Update_Call) Run(run func(ctx context.Context, db bun.IDB, sb *domain.StudentBill)) *MockStudentBillRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bun.IDB), args[2].(*domain.StudentBill))
	})
	return _c
}

func (_c *MockStudentBillRepo_Update_Call) Return(_a0 error) *MockStudentBillRepo_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStudentBillRepo_Update_Call) RunAndReturn(run func(context.Context, bun.IDB, *domain.StudentBill) error) *MockStudentBillRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, db, id, status, totalPaid
func (_m *MockStudentBillRepo) UpdateStatus(ctx context.Context, db bun.IDB, id uint, status string, totalPaid float64) error {
	ret := _m.Called(ctx, db, id, status, totalPaid)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uint, string, float64) error); ok {
		r0 = rf(ctx, db, id, status, totalPaid)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStudentBillRepo_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockStudentBillRepo_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - db bun.IDB
//   - id uint
//   - status string
//   - totalPaid float64
func (_e *MockStudentBillRepo_Expecter) UpdateStatus(ctx interface{}, db interface{}, id interface{}, status interface{}, totalPaid interface{}) *MockStudentBillRepo_UpdateStatus_Call {
	return &MockStudentBillRepo_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, db, id, status, totalPaid)}
}

func (_c *MockStudentBillRepo_UpdateStatus_Call) Run(run func(ctx context.Context, db bun.IDB, id uint, status string, totalPaid float64)) *MockStudentBillRepo_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bun.IDB), args[2].(uint), args[3].(string), args[4].(float64))
	})
	return _c
}

func (_c *MockStudentBillRepo_UpdateStatus_Call) Return(_a0 error) *MockStudentBillRepo_UpdateStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStudentBillRepo_UpdateStatus_Call) RunAndReturn(run func(context.Context, bun.IDB, uint, string, float64) error) *MockStudentBillRepo_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStudentBillRepo creates a new instance of MockStudentBillRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStudentBillRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStudentBillRepo {
	mock := &MockStudentBillRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
