// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bun "github.com/uptrace/bun"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/academic/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"

	user_authdomain "github.com/ahmadzakyarifin/schoolpay/internal/module/user_auth/domain"
)

// StudentRepo is an autogenerated mock type for the StudentRepo type
type StudentRepo struct {
	mock.Mock
}

// AddClassHistory provides a mock function with given fields: ctx, db, studentID, classID
func (_m *StudentRepo) AddClassHistory(ctx context.Context, db bun.IDB, studentID uint, classID uint) error {
	ret := _m.Called(ctx, db, studentID, classID)

	if len(ret) == 0 {
		panic("no return value specified for AddClassHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uint, uint) error); ok {
		r0 = rf(ctx, db, studentID, classID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BulkRestore provides a mock function with given fields: ctx, ids
func (_m *StudentRepo) BulkRestore(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkRestore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CountActive provides a mock function with given fields: ctx
func (_m *StudentRepo) CountActive(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountActive")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountActiveByPeriod provides a mock function with given fields: ctx, start, end, academicYear, classID, majorID
func (_m *StudentRepo) CountActiveByPeriod(ctx context.Context, start *time.Time, end *time.Time, academicYear int, classID uint, majorID uint, sort string) (int, error) {
	ret := _m.Called(ctx, start, end, academicYear, classID, majorID, sort)

	if len(ret) == 0 {
		panic("no return value specified for CountActiveByPeriod")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, uint, uint, string) (int, error)); ok {
		return rf(ctx, start, end, academicYear, classID, majorID, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *time.Time, *time.Time, int, uint, uint, string) int); ok {
		r0 = rf(ctx, start, end, academicYear, classID, majorID, sort)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *time.Time, *time.Time, int, uint, uint, string) error); ok {
		r1 = rf(ctx, start, end, academicYear, classID, majorID, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByClass provides a mock function with given fields: ctx, academicYear, classID, majorID
func (_m *StudentRepo) CountByClass(ctx context.Context, academicYear int, classID uint, majorID uint, sort string) (map[string]int, error) {
	ret := _m.Called(ctx, academicYear, classID, majorID, sort)

	if len(ret) == 0 {
		panic("no return value specified for CountByClass")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, uint, uint, string) (map[string]int, error)); ok {
		return rf(ctx, academicYear, classID, majorID, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, uint, uint, string) map[string]int); ok {
		r0 = rf(ctx, academicYear, classID, majorID, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, uint, uint, string) error); ok {
		r1 = rf(ctx, academicYear, classID, majorID, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByGender provides a mock function with given fields: ctx, academicYear, classID, majorID
func (_m *StudentRepo) CountByGender(ctx context.Context, academicYear int, classID uint, majorID uint, sort string) (map[string]int, error) {
	ret := _m.Called(ctx, academicYear, classID, majorID, sort)

	if len(ret) == 0 {
		panic("no return value specified for CountByGender")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, uint, uint, string) (map[string]int, error)); ok {
		return rf(ctx, academicYear, classID, majorID, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, uint, uint, string) map[string]int); ok {
		r0 = rf(ctx, academicYear, classID, majorID, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, uint, uint, string) error); ok {
		r1 = rf(ctx, academicYear, classID, majorID, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByMajor provides a mock function with given fields: ctx, academicYear, classID, majorID
func (_m *StudentRepo) CountByMajor(ctx context.Context, academicYear int, classID uint, majorID uint, sort string) (map[string]int, error) {
	ret := _m.Called(ctx, academicYear, classID, majorID, sort)

	if len(ret) == 0 {
		panic("no return value specified for CountByMajor")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, uint, uint, string) (map[string]int, error)); ok {
		return rf(ctx, academicYear, classID, majorID, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, uint, uint, string) map[string]int); ok {
		r0 = rf(ctx, academicYear, classID, majorID, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, uint, uint, string) error); ok {
		r1 = rf(ctx, academicYear, classID, majorID, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByStatus provides a mock function with given fields: ctx, academicYear, classID, majorID
func (_m *StudentRepo) CountByStatus(ctx context.Context, academicYear int, classID uint, majorID uint, sort string) (map[string]int, error) {
	ret := _m.Called(ctx, academicYear, classID, majorID, sort)

	if len(ret) == 0 {
		panic("no return value specified for CountByStatus")
	}

	var r0 map[string]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, uint, uint, string) (map[string]int, error)); ok {
		return rf(ctx, academicYear, classID, majorID, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, uint, uint, string) map[string]int); ok {
		r0 = rf(ctx, academicYear, classID, majorID, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, uint, uint, string) error); ok {
		r1 = rf(ctx, academicYear, classID, majorID, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CountByYear provides a mock function with given fields: ctx
func (_m *StudentRepo) CountByYear(ctx context.Context) (map[int]int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountByYear")
	}

	var r0 map[int]int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[int]int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[int]int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[int]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, db, s
func (_m *StudentRepo) Create(ctx context.Context, db bun.IDB, s *domain.Student) error {
	ret := _m.Called(ctx, db, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *domain.Student) error); ok {
		r0 = rf(ctx, db, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *StudentRepo) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx
func (_m *StudentRepo) FindAll(ctx context.Context) ([]domain.Student, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]domain.Student, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []domain.Student); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindAllPaginated provides a mock function with given fields: ctx, page, limit, search, filter, status, entryYear, classID, majorID, sort
func (_m *StudentRepo) FindAllPaginated(ctx context.Context, page int, limit int, search string, filter string, status string, entryYear int, classID uint, majorID uint, sort string) ([]domain.Student, int, error) {
	ret := _m.Called(ctx, page, limit, search, filter, status, entryYear, classID, majorID, sort)

	if len(ret) == 0 {
		panic("no return value specified for FindAllPaginated")
	}

	var r0 []domain.Student
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, int, uint, uint, string) ([]domain.Student, int, error)); ok {
		return rf(ctx, page, limit, search, filter, status, entryYear, classID, majorID, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, int, uint, uint, string) []domain.Student); ok {
		r0 = rf(ctx, page, limit, search, filter, status, entryYear, classID, majorID, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, string, int, uint, uint, string) int); ok {
		r1 = rf(ctx, page, limit, search, filter, status, entryYear, classID, majorID, sort)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string, string, int, uint, uint, string) error); ok {
		r2 = rf(ctx, page, limit, search, filter, status, entryYear, classID, majorID, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByEmail provides a mock function with given fields: ctx, email
func (_m *StudentRepo) FindByEmail(ctx context.Context, email string) (*domain.Student, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for FindByEmail")
	}

	var r0 *domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Student, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Student); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *StudentRepo) FindByID(ctx context.Context, id uint) (*domain.Student, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Student, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Student); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByIdentifiers provides a mock function with given fields: ctx, id
func (_m *StudentRepo) FindByIdentifiers(ctx context.Context, id string) (*domain.Student, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByIdentifiers")
	}

	var r0 *domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Student, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Student); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByNIK provides a mock function with given fields: ctx, nik
func (_m *StudentRepo) FindByNIK(ctx context.Context, nik string) (*domain.Student, error) {
	ret := _m.Called(ctx, nik)

	if len(ret) == 0 {
		panic("no return value specified for FindByNIK")
	}

	var r0 *domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Student, error)); ok {
		return rf(ctx, nik)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Student); ok {
		r0 = rf(ctx, nik)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, nik)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByNIS provides a mock function with given fields: ctx, nis
func (_m *StudentRepo) FindByNIS(ctx context.Context, nis string) (*domain.Student, error) {
	ret := _m.Called(ctx, nis)

	if len(ret) == 0 {
		panic("no return value specified for FindByNIS")
	}

	var r0 *domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Student, error)); ok {
		return rf(ctx, nis)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Student); ok {
		r0 = rf(ctx, nis)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, nis)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByNISN provides a mock function with given fields: ctx, nisn
func (_m *StudentRepo) FindByNISN(ctx context.Context, nisn string) (*domain.Student, error) {
	ret := _m.Called(ctx, nisn)

	if len(ret) == 0 {
		panic("no return value specified for FindByNISN")
	}

	var r0 *domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Student, error)); ok {
		return rf(ctx, nisn)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Student); ok {
		r0 = rf(ctx, nisn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, nisn)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindByPhone provides a mock function with given fields: ctx, phone
func (_m *StudentRepo) FindByPhone(ctx context.Context, phone string) (*domain.Student, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for FindByPhone")
	}

	var r0 *domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Student, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Student); ok {
		r0 = rf(ctx, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindIDsByTarget provides a mock function with given fields: ctx, targetType, targetID
func (_m *StudentRepo) FindIDsByTarget(ctx context.Context, targetType string, targetID uint) ([]uint, error) {
	ret := _m.Called(ctx, targetType, targetID)

	if len(ret) == 0 {
		panic("no return value specified for FindIDsByTarget")
	}

	var r0 []uint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) ([]uint, error)); ok {
		return rf(ctx, targetType, targetID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, uint) []uint); ok {
		r0 = rf(ctx, targetType, targetID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, uint) error); ok {
		r1 = rf(ctx, targetType, targetID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetClassHistory provides a mock function with given fields: ctx, studentID
func (_m *StudentRepo) GetClassHistory(ctx context.Context, studentID uint) ([]domain.ClassHistory, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetClassHistory")
	}

	var r0 []domain.ClassHistory
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.ClassHistory, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.ClassHistory); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ClassHistory)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDistinctEntryYears provides a mock function with given fields: ctx
func (_m *StudentRepo) GetDistinctEntryYears(ctx context.Context) ([]int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDistinctEntryYears")
	}

	var r0 []int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []int); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGenderDemographicsByClass provides a mock function with given fields: ctx, academicYear, classID, majorID
func (_m *StudentRepo) GetGenderDemographicsByClass(ctx context.Context, academicYear int, classID uint, majorID uint, sort string) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, academicYear, classID, majorID, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetGenderDemographicsByClass")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, uint, uint, string) ([]map[string]interface{}, error)); ok {
		return rf(ctx, academicYear, classID, majorID, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, uint, uint, string) []map[string]interface{}); ok {
		r0 = rf(ctx, academicYear, classID, majorID, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, uint, uint, string) error); ok {
		r1 = rf(ctx, academicYear, classID, majorID, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGenderDemographicsByMajor provides a mock function with given fields: ctx, academicYear, classID, majorID
func (_m *StudentRepo) GetGenderDemographicsByMajor(ctx context.Context, academicYear int, classID uint, majorID uint, sort string) ([]map[string]interface{}, error) {
	ret := _m.Called(ctx, academicYear, classID, majorID, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetGenderDemographicsByMajor")
	}

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, uint, uint, string) ([]map[string]interface{}, error)); ok {
		return rf(ctx, academicYear, classID, majorID, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, uint, uint, string) []map[string]interface{}); ok {
		r0 = rf(ctx, academicYear, classID, majorID, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, uint, uint, string) error); ok {
		r1 = rf(ctx, academicYear, classID, majorID, sort)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetParents provides a mock function with given fields: ctx, studentID
func (_m *StudentRepo) GetParents(ctx context.Context, studentID uint) ([]user_authdomain.User, error) {
	ret := _m.Called(ctx, studentID)

	if len(ret) == 0 {
		panic("no return value specified for GetParents")
	}

	var r0 []user_authdomain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]user_authdomain.User, error)); ok {
		return rf(ctx, studentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []user_authdomain.User); ok {
		r0 = rf(ctx, studentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]user_authdomain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, studentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStudentsByParentID provides a mock function with given fields: ctx, parentID
func (_m *StudentRepo) GetStudentsByParentID(ctx context.Context, parentID uint) ([]domain.Student, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetStudentsByParentID")
	}

	var r0 []domain.Student
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.Student, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.Student); ok {
		r0 = rf(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Student)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkParent provides a mock function with given fields: ctx, db, studentID, parentID, relation
func (_m *StudentRepo) LinkParent(ctx context.Context, db bun.IDB, studentID uint, parentID uint, relation string) error {
	ret := _m.Called(ctx, db, studentID, parentID, relation)

	if len(ret) == 0 {
		panic("no return value specified for LinkParent")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uint, uint, string) error); ok {
		r0 = rf(ctx, db, studentID, parentID, relation)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Restore provides a mock function with given fields: ctx, id
func (_m *StudentRepo) Restore(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ToggleStatus provides a mock function with given fields: ctx, id
func (_m *StudentRepo) ToggleStatus(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ToggleStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, db, s
func (_m *StudentRepo) Update(ctx context.Context, db bun.IDB, s *domain.Student) error {
	ret := _m.Called(ctx, db, s)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *domain.Student) error); ok {
		r0 = rf(ctx, db, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateActiveHistory provides a mock function with given fields: ctx, db, studentID, classID
func (_m *StudentRepo) UpdateActiveHistory(ctx context.Context, db bun.IDB, studentID uint, classID uint) error {
	ret := _m.Called(ctx, db, studentID, classID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateActiveHistory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uint, uint) error); ok {
		r0 = rf(ctx, db, studentID, classID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStudentRepo creates a new instance of StudentRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStudentRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *StudentRepo {
	mock := &StudentRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
