// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/support/domain"
	mock "github.com/stretchr/testify/mock"

	user_authdomain "github.com/ahmadzakyarifin/schoolpay/internal/module/user_auth/domain"
)

// SupportService is an autogenerated mock type for the SupportService type
type SupportService struct {
	mock.Mock
}

// Assign provides a mock function with given fields: ctx, conversationID, adminID
func (_m *SupportService) Assign(ctx context.Context, conversationID uint, adminID uint) error {
	ret := _m.Called(ctx, conversationID, adminID)

	if len(ret) == 0 {
		panic("no return value specified for Assign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = rf(ctx, conversationID, adminID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with given fields: ctx, conversationID
func (_m *SupportService) Close(ctx context.Context, conversationID uint) error {
	ret := _m.Called(ctx, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, conversationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// List provides a mock function with given fields: ctx, status, page, limit
func (_m *SupportService) List(ctx context.Context, status string, page int, limit int) ([]domain.Conversation, int, error) {
	ret := _m.Called(ctx, status, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Conversation
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]domain.Conversation, int, error)); ok {
		return rf(ctx, status, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []domain.Conversation); ok {
		r0 = rf(ctx, status, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, status, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, status, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Messages provides a mock function with given fields: ctx, conversationID
func (_m *SupportService) Messages(ctx context.Context, conversationID uint) ([]domain.Message, error) {
	ret := _m.Called(ctx, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for Messages")
	}

	var r0 []domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.Message, error)); ok {
		return rf(ctx, conversationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.Message); ok {
		r0 = rf(ctx, conversationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, conversationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RecordIncoming provides a mock function with given fields: ctx, phone, message, parent
func (_m *SupportService) RecordIncoming(ctx context.Context, phone string, message string, parent *user_authdomain.User) (*domain.Conversation, error) {
	ret := _m.Called(ctx, phone, message, parent)

	if len(ret) == 0 {
		panic("no return value specified for RecordIncoming")
	}

	var r0 *domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *user_authdomain.User) (*domain.Conversation, error)); ok {
		return rf(ctx, phone, message, parent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *user_authdomain.User) *domain.Conversation); ok {
		r0 = rf(ctx, phone, message, parent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, *user_authdomain.User) error); ok {
		r1 = rf(ctx, phone, message, parent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reply provides a mock function with given fields: ctx, conversationID, adminID, message
func (_m *SupportService) Reply(ctx context.Context, conversationID uint, adminID uint, message string) error {
	ret := _m.Called(ctx, conversationID, adminID, message)

	if len(ret) == 0 {
		panic("no return value specified for Reply")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, uint, string) error); ok {
		r0 = rf(ctx, conversationID, adminID, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSupportService creates a new instance of SupportService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSupportService(t interface {
	mock.TestingT
	Cleanup(func())
}) *SupportService {
	mock := &SupportService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
