// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bun "github.com/uptrace/bun"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/support/domain"
	mock "github.com/stretchr/testify/mock"
)

// SupportRepo is an autogenerated mock type for the SupportRepo type
type SupportRepo struct {
	mock.Mock
}

// Assign provides a mock function with given fields: ctx, db, conversationID, adminID
func (_m *SupportRepo) Assign(ctx context.Context, db bun.IDB, conversationID uint, adminID uint) error {
	ret := _m.Called(ctx, db, conversationID, adminID)

	if len(ret) == 0 {
		panic("no return value specified for Assign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uint, uint) error); ok {
		r0 = rf(ctx, db, conversationID, adminID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Close provides a mock function with given fields: ctx, db, conversationID
func (_m *SupportRepo) Close(ctx context.Context, db bun.IDB, conversationID uint) error {
	ret := _m.Called(ctx, db, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uint) error); ok {
		r0 = rf(ctx, db, conversationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateConversation provides a mock function with given fields: ctx, db, c
func (_m *SupportRepo) CreateConversation(ctx context.Context, db bun.IDB, c *domain.Conversation) error {
	ret := _m.Called(ctx, db, c)

	if len(ret) == 0 {
		panic("no return value specified for CreateConversation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *domain.Conversation) error); ok {
		r0 = rf(ctx, db, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateMessage provides a mock function with given fields: ctx, db, m
func (_m *SupportRepo) CreateMessage(ctx context.Context, db bun.IDB, m *domain.Message) error {
	ret := _m.Called(ctx, db, m)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *domain.Message) error); ok {
		r0 = rf(ctx, db, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindAll provides a mock function with given fields: ctx, status, page, limit
func (_m *SupportRepo) FindAll(ctx context.Context, status string, page int, limit int) ([]domain.Conversation, int, error) {
	ret := _m.Called(ctx, status, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Conversation
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]domain.Conversation, int, error)); ok {
		return rf(ctx, status, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []domain.Conversation); ok {
		r0 = rf(ctx, status, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, status, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, status, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *SupportRepo) FindByID(ctx context.Context, id uint) (*domain.Conversation, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Conversation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Conversation); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindMessages provides a mock function with given fields: ctx, conversationID
func (_m *SupportRepo) FindMessages(ctx context.Context, conversationID uint) ([]domain.Message, error) {
	ret := _m.Called(ctx, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for FindMessages")
	}

	var r0 []domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.Message, error)); ok {
		return rf(ctx, conversationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.Message); ok {
		r0 = rf(ctx, conversationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, conversationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOpenByPhone provides a mock function with given fields: ctx, phone
func (_m *SupportRepo) FindOpenByPhone(ctx context.Context, phone string) (*domain.Conversation, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for FindOpenByPhone")
	}

	var r0 *domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Conversation, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Conversation); ok {
		r0 = rf(ctx, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindOpenByParentID provides a mock function with given fields: ctx, parentID
func (_m *SupportRepo) FindOpenByParentID(ctx context.Context, parentID uint) (*domain.Conversation, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for FindOpenByParentID")
	}

	var r0 *domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Conversation, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Conversation); ok {
		r0 = rf(ctx, parentID)
	} else if ret.Get(0) != nil {
		r0 = ret.Get(0).(*domain.Conversation)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkRead provides a mock function with given fields: ctx, db, conversationID
func (_m *SupportRepo) MarkRead(ctx context.Context, db bun.IDB, conversationID uint) error {
	ret := _m.Called(ctx, db, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uint) error); ok {
		r0 = rf(ctx, db, conversationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateConversationPreview provides a mock function with given fields: ctx, db, id, lastMessage, unreadDelta
func (_m *SupportRepo) UpdateConversationPreview(ctx context.Context, db bun.IDB, id uint, lastMessage string, unreadDelta int) error {
	ret := _m.Called(ctx, db, id, lastMessage, unreadDelta)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConversationPreview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uint, string, int) error); ok {
		r0 = rf(ctx, db, id, lastMessage, unreadDelta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSupportRepo creates a new instance of SupportRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSupportRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SupportRepo {
	mock := &SupportRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
