// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bun "github.com/uptrace/bun"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/support/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockSupportRepo is an autogenerated mock type for the SupportRepo type
type MockSupportRepo struct {
	mock.Mock
}

type MockSupportRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSupportRepo) EXPECT() *MockSupportRepo_Expecter {
	return &MockSupportRepo_Expecter{mock: &_m.Mock}
}

// Assign provides a mock function with given fields: ctx, db, conversationID, adminID
func (_m *MockSupportRepo) Assign(ctx context.Context, db bun.IDB, conversationID uint, adminID uint) error {
	ret := _m.Called(ctx, db, conversationID, adminID)

	if len(ret) == 0 {
		panic("no return value specified for Assign")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uint, uint) error); ok {
		r0 = rf(ctx, db, conversationID, adminID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupportRepo_Assign_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Assign'
type MockSupportRepo_Assign_Call struct {
	*mock.Call
}

// Assign is a helper method to define mock.On call
//   - ctx context.Context
//   - db bun.IDB
//   - conversationID uint
//   - adminID uint
func (_e *MockSupportRepo_Expecter) Assign(ctx interface{}, db interface{}, conversationID interface{}, adminID interface{}) *MockSupportRepo_Assign_Call {
	return &MockSupportRepo_Assign_Call{Call: _e.mock.On("Assign", ctx, db, conversationID, adminID)}
}

func (_c *MockSupportRepo_Assign_Call) Run(run func(ctx context.Context, db bun.IDB, conversationID uint, adminID uint)) *MockSupportRepo_Assign_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bun.IDB), args[2].(uint), args[3].(uint))
	})
	return _c
}

func (_c *MockSupportRepo_Assign_Call) Return(_a0 error) *MockSupportRepo_Assign_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupportRepo_Assign_Call) RunAndReturn(run func(context.Context, bun.IDB, uint, uint) error) *MockSupportRepo_Assign_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with given fields: ctx, db, conversationID
func (_m *MockSupportRepo) Close(ctx context.Context, db bun.IDB, conversationID uint) error {
	ret := _m.Called(ctx, db, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uint) error); ok {
		r0 = rf(ctx, db, conversationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupportRepo_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSupportRepo_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
//   - db bun.IDB
//   - conversationID uint
func (_e *MockSupportRepo_Expecter) Close(ctx interface{}, db interface{}, conversationID interface{}) *MockSupportRepo_Close_Call {
	return &MockSupportRepo_Close_Call{Call: _e.mock.On("Close", ctx, db, conversationID)}
}

func (_c *MockSupportRepo_Close_Call) Run(run func(ctx context.Context, db bun.IDB, conversationID uint)) *MockSupportRepo_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bun.IDB), args[2].(uint))
	})
	return _c
}

func (_c *MockSupportRepo_Close_Call) Return(_a0 error) *MockSupportRepo_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupportRepo_Close_Call) RunAndReturn(run func(context.Context, bun.IDB, uint) error) *MockSupportRepo_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateConversation provides a mock function with given fields: ctx, db, c
func (_m *MockSupportRepo) CreateConversation(ctx context.Context, db bun.IDB, c *domain.Conversation) error {
	ret := _m.Called(ctx, db, c)

	if len(ret) == 0 {
		panic("no return value specified for CreateConversation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *domain.Conversation) error); ok {
		r0 = rf(ctx, db, c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupportRepo_CreateConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConversation'
type MockSupportRepo_CreateConversation_Call struct {
	*mock.Call
}

// CreateConversation is a helper method to define mock.On call
//   - ctx context.Context
//   - db bun.IDB
//   - c *domain.Conversation
func (_e *MockSupportRepo_Expecter) CreateConversation(ctx interface{}, db interface{}, c interface{}) *MockSupportRepo_CreateConversation_Call {
	return &MockSupportRepo_CreateConversation_Call{Call: _e.mock.On("CreateConversation", ctx, db, c)}
}

func (_c *MockSupportRepo_CreateConversation_Call) Run(run func(ctx context.Context, db bun.IDB, c *domain.Conversation)) *MockSupportRepo_CreateConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bun.IDB), args[2].(*domain.Conversation))
	})
	return _c
}

func (_c *MockSupportRepo_CreateConversation_Call) Return(_a0 error) *MockSupportRepo_CreateConversation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupportRepo_CreateConversation_Call) RunAndReturn(run func(context.Context, bun.IDB, *domain.Conversation) error) *MockSupportRepo_CreateConversation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMessage provides a mock function with given fields: ctx, db, m
func (_m *MockSupportRepo) CreateMessage(ctx context.Context, db bun.IDB, m *domain.Message) error {
	ret := _m.Called(ctx, db, m)

	if len(ret) == 0 {
		panic("no return value specified for CreateMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, *domain.Message) error); ok {
		r0 = rf(ctx, db, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupportRepo_CreateMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMessage'
type MockSupportRepo_CreateMessage_Call struct {
	*mock.Call
}

// CreateMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - db bun.IDB
//   - m *domain.Message
func (_e *MockSupportRepo_Expecter) CreateMessage(ctx interface{}, db interface{}, m interface{}) *MockSupportRepo_CreateMessage_Call {
	return &MockSupportRepo_CreateMessage_Call{Call: _e.mock.On("CreateMessage", ctx, db, m)}
}

func (_c *MockSupportRepo_CreateMessage_Call) Run(run func(ctx context.Context, db bun.IDB, m *domain.Message)) *MockSupportRepo_CreateMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bun.IDB), args[2].(*domain.Message))
	})
	return _c
}

func (_c *MockSupportRepo_CreateMessage_Call) Return(_a0 error) *MockSupportRepo_CreateMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupportRepo_CreateMessage_Call) RunAndReturn(run func(context.Context, bun.IDB, *domain.Message) error) *MockSupportRepo_CreateMessage_Call {
	_c.Call.Return(run)
	return _c
}

// FindAll provides a mock function with given fields: ctx, status, page, limit
func (_m *MockSupportRepo) FindAll(ctx context.Context, status string, page int, limit int) ([]domain.Conversation, int, error) {
	ret := _m.Called(ctx, status, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindAll")
	}

	var r0 []domain.Conversation
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]domain.Conversation, int, error)); ok {
		return rf(ctx, status, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []domain.Conversation); ok {
		r0 = rf(ctx, status, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) int); ok {
		r1 = rf(ctx, status, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = rf(ctx, status, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockSupportRepo_FindAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindAll'
type MockSupportRepo_FindAll_Call struct {
	*mock.Call
}

// FindAll is a helper method to define mock.On call
//   - ctx context.Context
//   - status string
//   - page int
//   - limit int
func (_e *MockSupportRepo_Expecter) FindAll(ctx interface{}, status interface{}, page interface{}, limit interface{}) *MockSupportRepo_FindAll_Call {
	return &MockSupportRepo_FindAll_Call{Call: _e.mock.On("FindAll", ctx, status, page, limit)}
}

func (_c *MockSupportRepo_FindAll_Call) Run(run func(ctx context.Context, status string, page int, limit int)) *MockSupportRepo_FindAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockSupportRepo_FindAll_Call) Return(_a0 []domain.Conversation, _a1 int, _a2 error) *MockSupportRepo_FindAll_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockSupportRepo_FindAll_Call) RunAndReturn(run func(context.Context, string, int, int) ([]domain.Conversation, int, error)) *MockSupportRepo_FindAll_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *MockSupportRepo) FindByID(ctx context.Context, id uint) (*domain.Conversation, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.Conversation, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.Conversation); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupportRepo_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockSupportRepo_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uint
func (_e *MockSupportRepo_Expecter) FindByID(ctx interface{}, id interface{}) *MockSupportRepo_FindByID_Call {
	return &MockSupportRepo_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockSupportRepo_FindByID_Call) Run(run func(ctx context.Context, id uint)) *MockSupportRepo_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSupportRepo_FindByID_Call) Return(_a0 *domain.Conversation, _a1 error) *MockSupportRepo_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupportRepo_FindByID_Call) RunAndReturn(run func(context.Context, uint) (*domain.Conversation, error)) *MockSupportRepo_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindMessages provides a mock function with given fields: ctx, conversationID
func (_m *MockSupportRepo) FindMessages(ctx context.Context, conversationID uint) ([]domain.Message, error) {
	ret := _m.Called(ctx, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for FindMessages")
	}

	var r0 []domain.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]domain.Message, error)); ok {
		return rf(ctx, conversationID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []domain.Message); ok {
		r0 = rf(ctx, conversationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, conversationID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupportRepo_FindMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindMessages'
type MockSupportRepo_FindMessages_Call struct {
	*mock.Call
}

// FindMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - conversationID uint
func (_e *MockSupportRepo_Expecter) FindMessages(ctx interface{}, conversationID interface{}) *MockSupportRepo_FindMessages_Call {
	return &MockSupportRepo_FindMessages_Call{Call: _e.mock.On("FindMessages", ctx, conversationID)}
}

func (_c *MockSupportRepo_FindMessages_Call) Run(run func(ctx context.Context, conversationID uint)) *MockSupportRepo_FindMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint))
	})
	return _c
}

func (_c *MockSupportRepo_FindMessages_Call) Return(_a0 []domain.Message, _a1 error) *MockSupportRepo_FindMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupportRepo_FindMessages_Call) RunAndReturn(run func(context.Context, uint) ([]domain.Message, error)) *MockSupportRepo_FindMessages_Call {
	_c.Call.Return(run)
	return _c
}

// FindOpenByPhone provides a mock function with given fields: ctx, phone
func (_m *MockSupportRepo) FindOpenByPhone(ctx context.Context, phone string) (*domain.Conversation, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for FindOpenByPhone")
	}

	var r0 *domain.Conversation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Conversation, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Conversation); ok {
		r0 = rf(ctx, phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Conversation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupportRepo_FindOpenByPhone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindOpenByPhone'
type MockSupportRepo_FindOpenByPhone_Call struct {
	*mock.Call
}

// FindOpenByPhone is a helper method to define mock.On call
//   - ctx context.Context
//   - phone string
func (_e *MockSupportRepo_Expecter) FindOpenByPhone(ctx interface{}, phone interface{}) *MockSupportRepo_FindOpenByPhone_Call {
	return &MockSupportRepo_FindOpenByPhone_Call{Call: _e.mock.On("FindOpenByPhone", ctx, phone)}
}

func (_c *MockSupportRepo_FindOpenByPhone_Call) Run(run func(ctx context.Context, phone string)) *MockSupportRepo_FindOpenByPhone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSupportRepo_FindOpenByPhone_Call) Return(_a0 *domain.Conversation, _a1 error) *MockSupportRepo_FindOpenByPhone_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupportRepo_FindOpenByPhone_Call) RunAndReturn(run func(context.Context, string) (*domain.Conversation, error)) *MockSupportRepo_FindOpenByPhone_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function with given fields: ctx, db, conversationID
func (_m *MockSupportRepo) MarkRead(ctx context.Context, db bun.IDB, conversationID uint) error {
	ret := _m.Called(ctx, db, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uint) error); ok {
		r0 = rf(ctx, db, conversationID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupportRepo_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type MockSupportRepo_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - db bun.IDB
//   - conversationID uint
func (_e *MockSupportRepo_Expecter) MarkRead(ctx interface{}, db interface{}, conversationID interface{}) *MockSupportRepo_MarkRead_Call {
	return &MockSupportRepo_MarkRead_Call{Call: _e.mock.On("MarkRead", ctx, db, conversationID)}
}

func (_c *MockSupportRepo_MarkRead_Call) Run(run func(ctx context.Context, db bun.IDB, conversationID uint)) *MockSupportRepo_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bun.IDB), args[2].(uint))
	})
	return _c
}

func (_c *MockSupportRepo_MarkRead_Call) Return(_a0 error) *MockSupportRepo_MarkRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupportRepo_MarkRead_Call) RunAndReturn(run func(context.Context, bun.IDB, uint) error) *MockSupportRepo_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateConversationPreview provides a mock function with given fields: ctx, db, id, lastMessage, unreadDelta
func (_m *MockSupportRepo) UpdateConversationPreview(ctx context.Context, db bun.IDB, id uint, lastMessage string, unreadDelta int) error {
	ret := _m.Called(ctx, db, id, lastMessage, unreadDelta)

	if len(ret) == 0 {
		panic("no return value specified for UpdateConversationPreview")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, bun.IDB, uint, string, int) error); ok {
		r0 = rf(ctx, db, id, lastMessage, unreadDelta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupportRepo_UpdateConversationPreview_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateConversationPreview'
type MockSupportRepo_UpdateConversationPreview_Call struct {
	*mock.Call
}

// UpdateConversationPreview is a helper method to define mock.On call
//   - ctx context.Context
//   - db bun.IDB
//   - id uint
//   - lastMessage string
//   - unreadDelta int
func (_e *MockSupportRepo_Expecter) UpdateConversationPreview(ctx interface{}, db interface{}, id interface{}, lastMessage interface{}, unreadDelta interface{}) *MockSupportRepo_UpdateConversationPreview_Call {
	return &MockSupportRepo_UpdateConversationPreview_Call{Call: _e.mock.On("UpdateConversationPreview", ctx, db, id, lastMessage, unreadDelta)}
}

func (_c *MockSupportRepo_UpdateConversationPreview_Call) Run(run func(ctx context.Context, db bun.IDB, id uint, lastMessage string, unreadDelta int)) *MockSupportRepo_UpdateConversationPreview_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(bun.IDB), args[2].(uint), args[3].(string), args[4].(int))
	})
	return _c
}

func (_c *MockSupportRepo_UpdateConversationPreview_Call) Return(_a0 error) *MockSupportRepo_UpdateConversationPreview_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupportRepo_UpdateConversationPreview_Call) RunAndReturn(run func(context.Context, bun.IDB, uint, string, int) error) *MockSupportRepo_UpdateConversationPreview_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSupportRepo creates a new instance of MockSupportRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSupportRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSupportRepo {
	mock := &MockSupportRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
