// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	config "github.com/ahmadzakyarifin/schoolpay/config"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/user_auth/domain"

	mock "github.com/stretchr/testify/mock"

	notificationdomain "github.com/ahmadzakyarifin/schoolpay/internal/module/notification/domain"

	usecase "github.com/ahmadzakyarifin/schoolpay/internal/module/user_auth/usecase"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// ActivateAccount provides a mock function with given fields: ctx, token, password
func (_m *UserService) ActivateAccount(ctx context.Context, token string, password string) (*domain.User, error) {
	ret := _m.Called(ctx, token, password)

	if len(ret) == 0 {
		panic("no return value specified for ActivateAccount")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.User, error)); ok {
		return rf(ctx, token, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.User); ok {
		r0 = rf(ctx, token, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, token, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveRefreshToken provides a mock function with given fields: ctx, userID, token, expiresAt
func (_m *UserService) SaveRefreshToken(ctx context.Context, userID uint, token string, expiresAt time.Time) error {
	ret := _m.Called(ctx, userID, token, expiresAt)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, time.Time) error); ok {
		r0 = rf(ctx, userID, token, expiresAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BulkDelete provides a mock function with given fields: ctx, ids
func (_m *UserService) BulkDelete(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}


// BulkResendNotification provides a mock function with given fields: ctx, ids, channel, cfg
func (_m *UserService) BulkResendNotification(ctx context.Context, ids []uint, channel string, cfg *config.Config) (*usecase.BulkResendResult, error) {
	ret := _m.Called(ctx, ids, channel, cfg)

	if len(ret) == 0 {
		panic("no return value specified for BulkResendNotification")
	}

	var r0 *usecase.BulkResendResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint, string, *config.Config) (*usecase.BulkResendResult, error)); ok {
		return rf(ctx, ids, channel, cfg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uint, string, *config.Config) *usecase.BulkResendResult); ok {
		r0 = rf(ctx, ids, channel, cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.BulkResendResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uint, string, *config.Config) error); ok {
		r1 = rf(ctx, ids, channel, cfg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BulkRestore provides a mock function with given fields: ctx, ids
func (_m *UserService) BulkRestore(ctx context.Context, ids []uint) error {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for BulkRestore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []uint) error); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Create provides a mock function with given fields: ctx, user, cfg
func (_m *UserService) Create(ctx context.Context, user *domain.User, cfg *config.Config) error {
	ret := _m.Called(ctx, user, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, *config.Config) error); ok {
		r0 = rf(ctx, user, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *UserService) Delete(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ExportExcel provides a mock function with given fields: ctx, search, role, filter, status
func (_m *UserService) ExportExcel(ctx context.Context, search string, role string, filter string, status string) ([]byte, error) {
	ret := _m.Called(ctx, search, role, filter, status)

	if len(ret) == 0 {
		panic("no return value specified for ExportExcel")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) ([]byte, error)); ok {
		return rf(ctx, search, role, filter, status)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) []byte); ok {
		r0 = rf(ctx, search, role, filter, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, search, role, filter, status)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx, role
func (_m *UserService) GetAll(ctx context.Context, role string) ([]domain.User, error) {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]domain.User, error)); ok {
		return rf(ctx, role)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []domain.User); ok {
		r0 = rf(ctx, role)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, role)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *UserService) GetByID(ctx context.Context, id uint) (*domain.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*domain.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *domain.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDependencyInfo provides a mock function with given fields: ctx, id
func (_m *UserService) GetDependencyInfo(ctx context.Context, id uint) (map[string]interface{}, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDependencyInfo")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (map[string]interface{}, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) map[string]interface{}); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNotifications provides a mock function with given fields: ctx, userID
func (_m *UserService) GetNotifications(ctx context.Context, userID uint) ([]notificationdomain.Notification, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetNotifications")
	}

	var r0 []notificationdomain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) ([]notificationdomain.Notification, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) []notificationdomain.Notification); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]notificationdomain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPaginated provides a mock function with given fields: ctx, page, limit, search, role, filter, status, sort
func (_m *UserService) GetPaginated(ctx context.Context, page int, limit int, search string, role string, filter string, status string, sort string) ([]domain.User, int, error) {
	ret := _m.Called(ctx, page, limit, search, role, filter, status, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetPaginated")
	}

	var r0 []domain.User
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string, string) ([]domain.User, int, error)); ok {
		return rf(ctx, page, limit, search, role, filter, status, sort)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int, string, string, string, string, string) []domain.User); ok {
		r0 = rf(ctx, page, limit, search, role, filter, status, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int, string, string, string, string, string) int); ok {
		r1 = rf(ctx, page, limit, search, role, filter, status, sort)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int, string, string, string, string, string) error); ok {
		r2 = rf(ctx, page, limit, search, role, filter, status, sort)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ResendNotification provides a mock function with given fields: ctx, id, channel, cfg
func (_m *UserService) ResendNotification(ctx context.Context, id uint, channel string, cfg *config.Config) error {
	ret := _m.Called(ctx, id, channel, cfg)

	if len(ret) == 0 {
		panic("no return value specified for ResendNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, *config.Config) error); ok {
		r0 = rf(ctx, id, channel, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Restore provides a mock function with given fields: ctx, id
func (_m *UserService) Restore(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Restore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ToggleStatus provides a mock function with given fields: ctx, id
func (_m *UserService) ToggleStatus(ctx context.Context, id uint) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ToggleStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, user, cfg
func (_m *UserService) Update(ctx context.Context, user *domain.User, cfg *config.Config) error {
	ret := _m.Called(ctx, user, cfg)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User, *config.Config) error); ok {
		r0 = rf(ctx, user, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
