// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/ahmadzakyarifin/schoolpay/internal/module/webhook/domain"
	mock "github.com/stretchr/testify/mock"
)

// WebhookRepo is an autogenerated mock type for the WebhookRepo type
type WebhookRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, log
func (_m *WebhookRepo) Create(ctx context.Context, log *domain.WebhookLog) error {
	ret := _m.Called(ctx, log)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.WebhookLog) error); ok {
		r0 = rf(ctx, log)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: ctx, eventID, status
func (_m *WebhookRepo) UpdateStatus(ctx context.Context, eventID string, status string) error {
	ret := _m.Called(ctx, eventID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, eventID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWebhookRepo creates a new instance of WebhookRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWebhookRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *WebhookRepo {
	mock := &WebhookRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
