// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WhatsAppService is an autogenerated mock type for the WhatsAppService type
type WhatsAppService struct {
	mock.Mock
}

// GetChatHistory provides a mock function with given fields: phone
func (_m *WhatsAppService) GetChatHistory(phone string) (interface{}, error) {
	ret := _m.Called(phone)

	if len(ret) == 0 {
		panic("no return value specified for GetChatHistory")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interface{}, error)); ok {
		return rf(phone)
	}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQR provides a mock function with no fields
func (_m *WhatsAppService) GetQR() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetQR")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStatus provides a mock function with no fields
func (_m *WhatsAppService) GetStatus() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RegisterWebhook provides a mock function with no fields
func (_m *WhatsAppService) RegisterWebhook() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RegisterWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendChatMessage provides a mock function with given fields: phone, message
func (_m *WhatsAppService) SendChatMessage(phone string, message string) error {
	ret := _m.Called(phone, message)

	if len(ret) == 0 {
		panic("no return value specified for SendChatMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(phone, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StartSession provides a mock function with no fields
func (_m *WhatsAppService) StartSession() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StopSession provides a mock function with no fields
func (_m *WhatsAppService) StopSession() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StopSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LogoutSession provides a mock function with no fields
func (_m *WhatsAppService) LogoutSession() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LogoutSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWhatsAppService creates a new instance of WhatsAppService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWhatsAppService(t interface {
	mock.TestingT
	Cleanup(func())
}) *WhatsAppService {
	mock := &WhatsAppService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
