// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockWhatsAppService is an autogenerated mock type for the WhatsAppService type
type MockWhatsAppService struct {
	mock.Mock
}

type MockWhatsAppService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWhatsAppService) EXPECT() *MockWhatsAppService_Expecter {
	return &MockWhatsAppService_Expecter{mock: &_m.Mock}
}

// GetChatHistory provides a mock function with given fields: phone
func (_m *MockWhatsAppService) GetChatHistory(phone string) (interface{}, error) {
	ret := _m.Called(phone)

	if len(ret) == 0 {
		panic("no return value specified for GetChatHistory")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (interface{}, error)); ok {
		return rf(phone)
	}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(phone)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWhatsAppService_GetChatHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChatHistory'
type MockWhatsAppService_GetChatHistory_Call struct {
	*mock.Call
}

// GetChatHistory is a helper method to define mock.On call
//   - phone string
func (_e *MockWhatsAppService_Expecter) GetChatHistory(phone interface{}) *MockWhatsAppService_GetChatHistory_Call {
	return &MockWhatsAppService_GetChatHistory_Call{Call: _e.mock.On("GetChatHistory", phone)}
}

func (_c *MockWhatsAppService_GetChatHistory_Call) Run(run func(phone string)) *MockWhatsAppService_GetChatHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockWhatsAppService_GetChatHistory_Call) Return(_a0 interface{}, _a1 error) *MockWhatsAppService_GetChatHistory_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWhatsAppService_GetChatHistory_Call) RunAndReturn(run func(string) (interface{}, error)) *MockWhatsAppService_GetChatHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetQR provides a mock function with no fields
func (_m *MockWhatsAppService) GetQR() ([]byte, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetQR")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWhatsAppService_GetQR_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQR'
type MockWhatsAppService_GetQR_Call struct {
	*mock.Call
}

// GetQR is a helper method to define mock.On call
func (_e *MockWhatsAppService_Expecter) GetQR() *MockWhatsAppService_GetQR_Call {
	return &MockWhatsAppService_GetQR_Call{Call: _e.mock.On("GetQR")}
}

func (_c *MockWhatsAppService_GetQR_Call) Run(run func()) *MockWhatsAppService_GetQR_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWhatsAppService_GetQR_Call) Return(_a0 []byte, _a1 error) *MockWhatsAppService_GetQR_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWhatsAppService_GetQR_Call) RunAndReturn(run func() ([]byte, error)) *MockWhatsAppService_GetQR_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function with no fields
func (_m *MockWhatsAppService) GetStatus() (string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWhatsAppService_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockWhatsAppService_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
func (_e *MockWhatsAppService_Expecter) GetStatus() *MockWhatsAppService_GetStatus_Call {
	return &MockWhatsAppService_GetStatus_Call{Call: _e.mock.On("GetStatus")}
}

func (_c *MockWhatsAppService_GetStatus_Call) Run(run func()) *MockWhatsAppService_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWhatsAppService_GetStatus_Call) Return(_a0 string, _a1 error) *MockWhatsAppService_GetStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWhatsAppService_GetStatus_Call) RunAndReturn(run func() (string, error)) *MockWhatsAppService_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterWebhook provides a mock function with no fields
func (_m *MockWhatsAppService) RegisterWebhook() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RegisterWebhook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWhatsAppService_RegisterWebhook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterWebhook'
type MockWhatsAppService_RegisterWebhook_Call struct {
	*mock.Call
}

// RegisterWebhook is a helper method to define mock.On call
func (_e *MockWhatsAppService_Expecter) RegisterWebhook() *MockWhatsAppService_RegisterWebhook_Call {
	return &MockWhatsAppService_RegisterWebhook_Call{Call: _e.mock.On("RegisterWebhook")}
}

func (_c *MockWhatsAppService_RegisterWebhook_Call) Run(run func()) *MockWhatsAppService_RegisterWebhook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWhatsAppService_RegisterWebhook_Call) Return(_a0 error) *MockWhatsAppService_RegisterWebhook_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWhatsAppService_RegisterWebhook_Call) RunAndReturn(run func() error) *MockWhatsAppService_RegisterWebhook_Call {
	_c.Call.Return(run)
	return _c
}

// SendChatMessage provides a mock function with given fields: phone, message
func (_m *MockWhatsAppService) SendChatMessage(phone string, message string) error {
	ret := _m.Called(phone, message)

	if len(ret) == 0 {
		panic("no return value specified for SendChatMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(phone, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWhatsAppService_SendChatMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendChatMessage'
type MockWhatsAppService_SendChatMessage_Call struct {
	*mock.Call
}

// SendChatMessage is a helper method to define mock.On call
//   - phone string
//   - message string
func (_e *MockWhatsAppService_Expecter) SendChatMessage(phone interface{}, message interface{}) *MockWhatsAppService_SendChatMessage_Call {
	return &MockWhatsAppService_SendChatMessage_Call{Call: _e.mock.On("SendChatMessage", phone, message)}
}

func (_c *MockWhatsAppService_SendChatMessage_Call) Run(run func(phone string, message string)) *MockWhatsAppService_SendChatMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockWhatsAppService_SendChatMessage_Call) Return(_a0 error) *MockWhatsAppService_SendChatMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWhatsAppService_SendChatMessage_Call) RunAndReturn(run func(string, string) error) *MockWhatsAppService_SendChatMessage_Call {
	_c.Call.Return(run)
	return _c
}

// StartSession provides a mock function with no fields
func (_m *MockWhatsAppService) StartSession() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWhatsAppService_StartSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartSession'
type MockWhatsAppService_StartSession_Call struct {
	*mock.Call
}

// StartSession is a helper method to define mock.On call
func (_e *MockWhatsAppService_Expecter) StartSession() *MockWhatsAppService_StartSession_Call {
	return &MockWhatsAppService_StartSession_Call{Call: _e.mock.On("StartSession")}
}

func (_c *MockWhatsAppService_StartSession_Call) Run(run func()) *MockWhatsAppService_StartSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWhatsAppService_StartSession_Call) Return(_a0 error) *MockWhatsAppService_StartSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWhatsAppService_StartSession_Call) RunAndReturn(run func() error) *MockWhatsAppService_StartSession_Call {
	_c.Call.Return(run)
	return _c
}

// StopSession provides a mock function with no fields
func (_m *MockWhatsAppService) StopSession() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for StopSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWhatsAppService_StopSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopSession'
type MockWhatsAppService_StopSession_Call struct {
	*mock.Call
}

// StopSession is a helper method to define mock.On call
func (_e *MockWhatsAppService_Expecter) StopSession() *MockWhatsAppService_StopSession_Call {
	return &MockWhatsAppService_StopSession_Call{Call: _e.mock.On("StopSession")}
}

func (_c *MockWhatsAppService_StopSession_Call) Run(run func()) *MockWhatsAppService_StopSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWhatsAppService_StopSession_Call) Return(_a0 error) *MockWhatsAppService_StopSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWhatsAppService_StopSession_Call) RunAndReturn(run func() error) *MockWhatsAppService_StopSession_Call {
	_c.Call.Return(run)
	return _c
}

// LogoutSession provides a mock function with no fields
func (_m *MockWhatsAppService) LogoutSession() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LogoutSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWhatsAppService_LogoutSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogoutSession'
type MockWhatsAppService_LogoutSession_Call struct {
	*mock.Call
}

// LogoutSession is a helper method to define mock.On call
func (_e *MockWhatsAppService_Expecter) LogoutSession() *MockWhatsAppService_LogoutSession_Call {
	return &MockWhatsAppService_LogoutSession_Call{Call: _e.mock.On("LogoutSession")}
}

func (_c *MockWhatsAppService_LogoutSession_Call) Run(run func()) *MockWhatsAppService_LogoutSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWhatsAppService_LogoutSession_Call) Return(_a0 error) *MockWhatsAppService_LogoutSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWhatsAppService_LogoutSession_Call) RunAndReturn(run func() error) *MockWhatsAppService_LogoutSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockWhatsAppService creates a new instance of MockWhatsAppService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWhatsAppService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWhatsAppService {
	mock := &MockWhatsAppService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
