-- +goose Up
CREATE TABLE IF NOT EXISTS classes (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    jurusan_id INT UNSIGNED,
    grade INT NOT NULL,
    is_active TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP NULL,
    CONSTRAINT fk_class_jurusan FOREIGN KEY (jurusan_id) REFERENCES majors(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- +goose Down
DROP TABLE IF EXISTS classes;
