-- +goose Up
ALTER TABLE webhook_logs
  MODIFY COLUMN event_id VARCHAR(191),
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER created_at,
  ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL DEFAULT NULL AFTER updated_at;

-- +goose Down
ALTER TABLE webhook_logs
  DROP COLUMN IF EXISTS deleted_at,
  DROP COLUMN IF EXISTS updated_at,
  MODIFY COLUMN event_id VARCHAR(100);
