-- +goose Up
ALTER TABLE deposit_movements
MODIFY COLUMN reason ENUM('OVERPAYMENT', 'BILL_VOIDED', 'BILL_AMOUNT_REDUCED', 'MANUAL_DEPOSIT', 'PAY_BILL', 'WITHDRAWAL') NOT NULL;

-- +goose Down
UPDATE deposit_movements SET reason = 'MANUAL_DEPOSIT' WHERE reason = 'BILL_AMOUNT_REDUCED';
ALTER TABLE deposit_movements
MODIFY COLUMN reason ENUM('OVERPAYMENT', 'BILL_VOIDED', 'MANUAL_DEPOSIT', 'PAY_BILL', 'WITHDRAWAL') NOT NULL;
